### ISSUE TITLE
Caliche Stone not usable for Saltpeter at Furnace, but works in Extraction Lab?

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#100]
I'm just wondering if this is intentional and curious as to why. The FrackinUniverse Wiki says ( http://frackinuniverse.wikia.com/wiki/Saltpeter ) Saltpeter is "Created by smelting Caliche Stone, Limestone, or Unrefined Chert in a furnace." However, even with an Atomic Furnace, Caliche Stone is not an option. Why was Caliche Stone -> Saltpeter removed from the Furnace? Strangely the Extraction Lab will convert Caliche Stone to Saltpeter (and Iodine).

**Comment by sayterdarkwynd** [comment]
have you not tried it in a fission furnace?

**Comment by sayterdarkwynd** [comment]
if its not present at all, thats a bug and ill get it fixed though

**Comment by sayterdarkwynd** [comment]
aaand yes, youre right. its missing. thanks.
