### ISSUE TITLE
Suggestion: Extraction Lab and Raw Minerals

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#101]
A majority of blocks will yield Raw Minerals, even blocks that are hard to come by or which should obviously return something else. Ice yields 2-3 Raw Minerals (& 1 Nitrogen)? Why shouldn't Ice yield Water? Sulphuric Dirt and Sulphuric Stone? Why don't these yield Sulphur?

Burning Volcanic Rock yields only Raw Minerals? In contrast, Cooled Volcanic Rock, Volcanic Rock, Magmarock, and Obsidian yield Ammonium Sulfate. (Obsidian yields Obsidian Shards, which convert to Ammonium Sulfate.) Actually, since Burning Volcanic Rock glows bright orange and is rather rare and hard to acquire (it burns you), I think it should yield 1 Core Fragment.

**Comment by sayterdarkwynd** [comment]
not sure this is an "issue" so much as a request.

that said, extraction recipes need overhauls here and there and a few of these are good points. I'll look into some adjustments.

**Comment by sayterdarkwynd** [comment]
as for burning volcanic rock: its not rare. Almost the entire surface of Infernus worlds are covered in it.

unless you mean the red-hot cobble stones...in which case, those already extract for core frags. I think you mean the infernus ones though.
