### ISSUE TITLE
[Suggestion] Science outpost spoiling a lot

### ISSUE THREAD

**Issue by Leosky** [sayterdarkwynd/FrackinUniverse#1029]
The quest that send you to the outpost give you access to every top tier station, you can use them to craft what ever you want and you got spoiled a lot of stuff just interacting with the station. 

May be it could be a good idea to replace the stations in the outpost to static uninteractables ones could be a way to avoid this ?

**Comment by shadow-absorber** [comment]
@Leosky this is being worked on somewhat as we have plans to rework the entire science outpost.....
