### ISSUE TITLE
Extraction lab possibly missing material

### ISSUE THREAD

**Issue by FormalRiceFarmer** [sayterdarkwynd/FrackinUniverse#103]
the extraction lab only extracts from normal honey material and not the red looking one (by the same name)
![ss 2016-08-05 at 07 01 02](https://cloud.githubusercontent.com/assets/1855792/17436069/7dd63784-5ada-11e6-9b60-af80d079aa91.png)

**Comment by FormalRiceFarmer** [comment]
normal is called
`honeycombmaterial`
and red is simply called
`honeycombmaterial`

**Comment by sayterdarkwynd** [comment]
thanks. addressing this now
