### ISSUE TITLE
Unable to import previous saves.

### ISSUE THREAD

**Issue by sobfiggis** [sayterdarkwynd/FrackinUniverse#1030]
http://steamcommunity.com/workshop/filedetails/?id=837530354

starbound.log can be found at https://gist.github.com/sobfiggis/8f7500a932040fbb5ffd833d3f900c08#file-starbound-log

[Error] Failed to valid player with uuid 823224577324e4f7348d1a2be0a14e21 : (JsonException) Json::get(2) out of range

Running on linux if that makes any difference to starbound mods.

**Comment by sobfiggis** [comment]
Disregard... http://steamcommunity.com/sharedfiles/filedetails/?id=821455287

> "IMPORTANT: Adding this in WILL remove all existing characters from the character list. There is absolutely *nothing* that can be done about this, due to how the feature works. Install this only if you intend a fresh playthrough." 

I understand using the modpack is secondary but could you put a small disclaimer about this? I assumed incorrectly the FAQ applied to the modpack you put together.

> Q: Do I need to delete my characters and universe before I start? Will it work with the character I already have?
> (or any possible variation of this question)
> A: No, you do not.
> However, you will need to travel a fair ways away on your starmap in order to generate the new biome types. Generally a few seconds will do. So yes, it will work with your existing character. I recommend a clean universe, personally, but that's only if you absolutely want to have FU planets right near your starting location.
>

**Comment by whismerhill** [comment]
the collection is simply not FU. you can close this.
even if you wrote on the collection that each description needs to be read, people will likely not read it.

Either way it's hugely recommended to start over with a new universe, or else you'll have to travel far away to generate new FU stars/planets

**Comment by sobfiggis** [comment]
Understood and closed but it would have saved at least one person a good 20-30 minutes :).Thanks again for the work on the mod.
