### ISSUE TITLE
Suggestion for Extraction Lab - Extract Sulfuric Acid, and 'possibly create it'

### ISSUE THREAD

**Issue by koalalord9999** [sayterdarkwynd/FrackinUniverse#105]
I just tried putting some Sulfuric Acid into the Extraction lab, nothing happened. So I looked online to find out what Sulfuric acid was made of, it's made of H2O4S, or in game terms 2 hydrogen, 2 Oxygen, and one Sulfur. This would have to remove the current recipe to create sulfuric acid, by placing 1 Sulphur into the 
+{inputs = { liquidsulphuricacid=10 }, outputs = { fu_oxygen=2, fu_hydrogen=2, sulphur=1 }, time = 2.25},
+{inputs = { sulphur=1, fu_oxygen=2, fu_hydrogen=2 }, outputs = { liquidsulphuricacid=10 }, time = 5.0},
This second one, is to possibly create sulfuric acid, but I'm unsure if the extraction lab can accept multiple inputs
-{inputs = { sulphur=1 }, outputs = { liquidsulphuricacid=2 }, time = 1.0},

Takes awhile to process because the machine is fighting the acid from eating the interior :)

**Comment by sayterdarkwynd** [comment]
its plentiful enough that i dont think its really necessary.
