### ISSUE TITLE
Damaged World

### ISSUE THREAD

**Issue by Reginald-Halifrax** [sayterdarkwynd/FrackinUniverse#1052]
The "Frozen Wastes" mission is currently damaged and after a short visit there, it returns a 

[Error] Exception caught in client main-loop
(EofException) Failed to read full buffer in readFull, eof reached.

and sends you back to the main menu. This makes the mission unplayable.

that's about all I have to say.

**Comment by sayterdarkwynd** [comment]
I can't replicate this. never have. Others experience it, no idea why. Log hasnt helped.

**Comment by nihiluis** [comment]
weird issue policy

**Comment by Reginald-Halifrax** [comment]
please dont necro a dead issue, he even fixed this issue recently.
