### ISSUE TITLE
Physics Field 2: A+W+Space provides no effect.

### ISSUE THREAD

**Issue by Halvaard** [sayterdarkwynd/FrackinUniverse#1143]
I can get all other directions to float, but back+up will not trigger.

**Comment by sayterdarkwynd** [comment]
its based on velocity. Floating is not the intent of the tech.

**Comment by Halvaard** [comment]
I guess I worded that poorly, but there is an issue, unless it's somehow my keyboard.

Rather than float, I can get it to fly me in all directions except "Left+Up".
