### ISSUE TITLE
Why are you required to have obtained Quietus Bar to learn Morphite Manipulator? As the ONLY pre-requisite

### ISSUE THREAD

**Issue by koalalord9999** [sayterdarkwynd/FrackinUniverse#117]
So, I just went through looked in the code, saw I needed to craft a quietus bar to learn how to make the Morphite Manipulator. This doesn't make much sense as you don't even need Quietus to craft the Manipulator. I think, if anything, you should learn how to craft the Morphite Manipulator, when you first obtain a Morphite Bar, or AI Chip, or the Nuclear Core, or, to continue the trend of making the mining weapons, learn it when you craft the KX-1 Mining Beam. It would only make sense that you learn the Manipulator when you pickup something that is required to make the tool itself. Not something that was made just because, and not used at all in the creation of the tool.

EDIT - Found where you need the Quietus, it's in the pyrite bars (which I got from a chest on an unreal difficulty world Lol) Doesn't change the fact that I had all the materials needed, and still couldn't craft it.

OT EDIT - Would it be possible to also add the Matter Manipulator you get from these upgrades to the default one, EG, when I press R (or whatever you have your MM keybind set to) it chooses this new matter manipulator? Is that even possible? If so, and if not too difficult, could that be implemented? That would be awesome xD

**Comment by sayterdarkwynd** [comment]
it used to need the quietus.

could have made this post a LOT shorter dude.   "morphite manipulator needs Quietus. why?"

done.
