### ISSUE TITLE
Research Item Disapearing

### ISSUE THREAD

**Issue by Halvaard** [sayterdarkwynd/FrackinUniverse#1178]
When producing Research via Extractor or Item Generation nothing is shown in the inventory.

**Comment by Halvaard** [comment]
Oh it's stored in the tricorder, nevermind.

**Comment by WatcherCCG** [comment]
Sayter tried to code it into the inventory next to pixels and ancient essence, but that spot is apparently hardcoded and untouchable, so research is stored in the tricorder instead.
