### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by rococode** [sayterdarkwynd/FrackinUniverse#1186]
For such a huge project it would probably be a good idea to have a license, right? If only [to guard against annoyances like this](https://github.com/sayterdarkwynd/FrackinUniverse/issues/1116).

Just thought I'd suggest it in case it was something that was forgotten about! It'd take all of 10 minutes to pick a license and stick it into the root.

**Comment by sayterdarkwynd** [comment]
lol. yea, ill do that just to cover our ass. I sure wont be removing content given by a former team member who is on record saying we can use that content.
