### ISSUE TITLE
Inconsistency in Crafting Material Rarity

### ISSUE THREAD

**Issue by Aussiemon** [sayterdarkwynd/FrackinUniverse#120]
Plutonium rod common, ore is uncommon.
Zerchesium bar rare, ore is uncommon.
Moonstone bar uncommon, ore is common.
Triangulum pyramid rare, ore is common.
Prismicite is legendary, shard is uncommon.

I believe these ores are the only ingredients in their refined forms, so the transition seems strange alongside most other materials. More minor nitpicky stuff, sorry :+1: 

![Example](https://cloud.githubusercontent.com/assets/13663574/17502916/f8ac5652-5da8-11e6-889d-bc4b0ab8bd8a.jpg)
.

**Comment by sayterdarkwynd** [comment]
what? Im not sure what you are saying. uranium ore makes rods. so its rarity correlates only to the rarity of uranium, which is common enough now that it is simple to acquire.

or do you mean in terms of recipes that require them? in which case, that is also why we have pyreite, isogen, trianglium, nocxium and xitrhicite. They soak a lot of that extra stuff up and are pretty damned useful to have.

Going by the color of the items border is not an accurate way to determine much. Sometimes I just forget to swap the color for a long time :) I should probably revisit that aspect of it.

**Comment by Aussiemon** [comment]
The colors of those ten item borders are what I'm referring to. All other bars (at least that I've seen) have the same item border as their ore form. This bunch do not.

No problems with the actual appearance rate of the materials :)

**Comment by renbear67** [comment]
I understand what you mean. That's bugged me for a while. I'd suggest putting together a proposal, @Aussiemon , and we'll implement it.

**Comment by sayterdarkwynd** [comment]
or just set all ores to the same rarity and be done with it.

I'd prefer tiered though, since people seem to dig that shit. 

id say anything found tier3 and below is white. Anything else needs to be graded.

**Comment by Aussiemon** [comment]
My proposal is that:

- Plutonium rod's item border be set to green.
- Zerchesium bar's item border be set to green.
- Moonstone ore's item border be set to green.
-Triangulum ore's item border be set to blue.
- Either prismicite's and prisilite's item borders be set to blue (prisilite is very common on chromatic worlds), or that prisilite's item border be set to purple and its appearance rate reduced to be similar to that of densium.

Also suggested:

- Lunari shard and lunari ore's item borders be set to green (making crystal tiers: prisilite (blue) > lunari (green) > crystal (white))

I haven't looked much into the tier of goods that these items produce, so a full look might still be necessary at some point, but this would at least provide consistency pending an in-depth revisit.

**Comment by sayterdarkwynd** [comment]
well, thats all well and good except...

prisilite is pretty much ONLY common on Chromatic worlds. as was intended. It's rare everywhere else.

Lunari is tier 1-2.
Prisilite is about tier 4-5

so that wont be getting changed. The other items are swapped for consistency though
