### ISSUE TITLE
Growing Trays Not Growing

### ISSUE THREAD

**Issue by MokahTGS** [sayterdarkwynd/FrackinUniverse#1206]
Since the latest patch with the growing tray updates I cannot get them to grow. I put a bunch (100) of seeds in, a bunch of water (100) and nothing happens. Seeds are taken in, water is used, but nothing spouts. How long are they supposed to take to grow? Is fertilizer required now? I've idled next to my trays for over an hour and nothing happens...just water getting used.

**Update**  I've now tried it with 100 Fertilizer and its still not growing.

https://www.dropbox.com/s/8fpq6dzc7gmvny1/nogrow1.jpg?dl=0

**Comment by kittycat2002** [comment]
Please post a log and what seed is that?

**Comment by MokahTGS** [comment]
Why did this get closed?

**Comment by gamrguy** [comment]
It's been closed because it's been fixed. The fix is live.

**Comment by MokahTGS** [comment]
Great thx.   Good info too.   What about water usage?
