### ISSUE TITLE
Research item

### ISSUE THREAD

**Issue by rtm516** [sayterdarkwynd/FrackinUniverse#1222]
When I pick up a 'Research' bottle nothing appears in my inventory and when i try and pull it out of an inventory such as an extractor it just disappears.

Version: 5.5.99
Starbound version: 1.3.3
This is all while connected to my own server and with no other mods installed.

**Comment by XDGrangerDX** [comment]
The research item is a currency item - it behaves exactly like pixels and essence do. You can find your balance in the tricoder UI.

**Comment by rtm516** [comment]
Where do you get them as there not explained on the wiki. http://frackinuniverse.wikia.com/wiki/Personal_Tricorder

**Comment by XDGrangerDX** [comment]
You get a free tricoder by showing Vindasj a Machining Table. You can also craft a Tricoder at the Machining Table later on.
