### ISSUE TITLE
Starting quest bug

### ISSUE THREAD

**Issue by KieroAshkore** [sayterdarkwynd/FrackinUniverse#1230]
Seems I have encountered a bug. After starting a new character and completing the cavern dungeon, it has glitched and made it so I am unable to start the main story as Esther just uses her "I'll be here if you need me dear." line. I am unsure what triggered the problem, but just thought I would leave this here to state that there is indeed an issue.

**Comment by sayterdarkwynd** [comment]
This is exceptionally unhelpful, as this could be caused by other mods or you simply not having specific gear from the quest / not following instruction,  or something else entirely.

I've run the quest *multiple* times and never had that occur. So, I need to know more.
