### ISSUE TITLE
"Underground gaps"

### ISSUE THREAD

**Issue by User353243** [sayterdarkwynd/FrackinUniverse#124]
Great work so far!

Unfortunately, there are large "underground gaps" (horizontal) on planets. You can find them after digging awhile.

**Comment by Aussiemon** [comment]
Is this what you're referring to?

![horizontalgap](https://cloud.githubusercontent.com/assets/13663574/17507380/90d38608-5dcc-11e6-8841-e2ab1fe3f840.jpg)

**Comment by User353243** [comment]
Absolutely! Any ideas how to prevent this issue?

**Comment by koalalord9999** [comment]
It's part of the base generation, not the easiest of things to work around I would imagine, it's just to guarentee that none of the natural landscape ends up falling into or on the base that generates at the bottom. (As my guess that is...)

**Comment by User353243** [comment]
Thanks for the answer. I also found a gap filled with liquid nitrogen on a metallic moon. It seems more like a bug to me.
