### ISSUE TITLE
Tray Issues

### ISSUE THREAD

**Issue by mudparr** [sayterdarkwynd/FrackinUniverse#1245]
Not sure whether to post here or forums or both.  Posted on forums as well in case others were having issue.

Log attached.

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/1671733/starbound.log)

So I'm having an issue after the update with trays. Growing trays will continue to work fine until the moment when they are supposed to give the final crop output at which point they crash the game with a world ship error. The final growth has happened and when logging back in the item is available and things start growing again, but it will crash again when growth is complete. This makes things crazy if you have 20 growing trays on your ship.

Hydroponics trays are acting even weirder. They take all seeds (only been testing with Algae), they will grow once, crash the game and then never work again. 

At first I thought it was a mod interaction or just some old stuff hanging around so I uninstalled, deleted all remaining files, reinstalled and tested using admin commands, same result. Repeated again (fresh install), this time removing all mods except FU, FR, and FM, but had the exact same result. 

If there is a better place to report this or if you need more information please let me know. This is unfortunately game breaking right now.

**Comment by gamrguy** [comment]
Thanks for bringing this to my attention. Part of the code that I revised didn't check properly for a certain case regarding updating the animation. I'm uploading a PR that fixes this now.
