### ISSUE TITLE
Growing and Hydroponics Trays still not working as intended

### ISSUE THREAD

**Issue by mudparr** [sayterdarkwynd/FrackinUniverse#1247]
First off let me say thanks for looking at that issue so quickly. I'm always very appreciative of all the hard work that mod authors put in. 

In relation the the hot fix #1246  for   #1245 It appears to have now created a new issue/not resolved one of the original issues.

1. Growing Trays now get to about half growth stage in their animation and then start producing crops at the rate of about 1 per second (on the tested algae), while reducing water at a similar rate. While funny for a minute, this is obviously not the intended operation of a growing tray.  Plus side, they don't crash anymore.

2. Hydroponics Trays do nothing at all.  Did a fresh install to check. They do not crash, but they also simply do not do anything. Put seeds in, seeds are not taken into tray (do not disappear). Water level does not change. Tray does not light up when wired up to power. Etc. etc. Not my first play through of FU so  I understand how they are supposed to work.

Log attached, but there are no crashes so not sure how useful.

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/1672171/starbound.log)

**Comment by sayterdarkwynd** [comment]
yea, were addressing it thanks
