### ISSUE TITLE
ITD Category not working for Backpack items

### ISSUE THREAD

**Issue by Malkierian** [sayterdarkwynd/FrackinUniverse#1259]
The Category sort in the ITD doesn't work for backpack items.  I've had to put in a separate entry for blueprints, EPP augments, weapons, and upgrade components. Armor, musical instruments, medicine, and other beamguns are stuck in my global chest.  This functionality has worked as expected, however, for the other four inventory tabs.  Here's my ITD:
https://i.gyazo.com/81b656e3c2cda31958a12eb6a869941b.png

Here's the inventory it's supposed to go into:
https://i.gyazo.com/7c4103b1db440a41d6fb7b941e159cde.png

And here's the inventory it's supposed to be pulling from:
https://i.gyazo.com/b663603096fc1ea8ad04be60ab4c7ae3.png

**Comment by Kherae** [comment]
Not a bug. It's not about inventory tabs.
https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/scripts/kheAA/transferconfig.config
