### ISSUE TITLE
Quest: Why do they hate Kevin

### ISSUE THREAD

**Issue by Katorone** [sayterdarkwynd/FrackinUniverse#1268]
I'm on the latest release (5.6.1881)

In the quest "Why do they hate Kevin" I'm told to use the "Sewing wheel" to make a Booster Croptop.  This recipe isn't available on the Spinning wheel (not upgraded), but can be accessed on the Medieval Workbench.

**Comment by sayterdarkwynd** [comment]
Yes it is. You simply have not unlocked it there yet. Craft polymer.
