### ISSUE TITLE
Circular recipes

### ISSUE THREAD

**Issue by Katorone** [sayterdarkwynd/FrackinUniverse#1269]
I'm on the latest version.  Still exploring and discovering new things, so I'm unsure if there are future recipes that offer an alternative way to craft these items.

Flame turret requires an incinerator to craft. The incinerator requires a flame turret to craft.
Laser turret requires a laser gun to craft.  The laser gun requires a laser turret to craft.
Both in the Electronics center.

**Comment by sayterdarkwynd** [comment]
False. Those are "unturreting your turret" recipes so you can get the gun back or vice versa
