### ISSUE TITLE
Unable to craft Bone Wand

### ISSUE THREAD

**Issue by LycanBlackpaw** [sayterdarkwynd/FrackinUniverse#1344]
Using Frackin' Universe 5.6.214

I noticed this issue for a few versions, but the bone wand recipe is not unlocked when picking up a core fragment. I have all the ingredients (sharpened claws, bone, a core fragment) but it doesn't show up in the Armorworks or on an Anvil. Is this a bug or an unnoted change?

**Comment by sayterdarkwynd** [comment]
it works perfectly fine. Tested on 5 separate characters including newly created ones.

the issue, therefore, is another mod patching the corefragments incorrectly, overriding, or just conflicting
