### ISSUE TITLE
Densinium armor

### ISSUE THREAD

**Issue by User353243** [sayterdarkwynd/FrackinUniverse#138]
At the moment the densinium armor makes the player immune to almost every environmental hazard. Additional it gives great protection. I am not using any EPP at all. I suggest nerfing it or to make it very hard to get.

**Comment by Aussiemon** [comment]
I don't believe it gives breathing, proto, mud/slush/slime, bio-ooze, poison, or insanity protections; to name a few. There are other ways to get heat, cold, and radiation protection in a single package (not three pieces). The stat bonuses are fairly similar to other end-game sets.

It's supposed to be fairly difficult to get though; so if you got it without much trouble, maybe it could use some added difficulty. I think it's in a good position already, personally.
