### ISSUE TITLE
Elder altar

### ISSUE THREAD

**Issue by User353243** [sayterdarkwynd/FrackinUniverse#141]
I avoid using the wiki because i want to find out everything by myself. Up until now I hav no clue how to use the elder altar. Are there any little hints in the game? If not, I would suggest adding them.

**Comment by User353243** [comment]
I just found a few hints.

**Comment by sayterdarkwynd** [comment]
stop using this to report things like this. 

it is for ISSUES, not clues on how to play or get items.,
