### ISSUE TITLE
Bees on a Space Station

### ISSUE THREAD

**Issue by LycanBlackpaw** [sayterdarkwynd/FrackinUniverse#1423]
I read in the FU wiki (the comments on [this](https://frackinuniverse.wikia.com/wiki/Bees:_Basics) page) that at one point, bees would work 24/7 on space stations. So, I built a space station, put a bunch of giant apiaries on it, and stuck bees inside...and they aren't working.

When exactly was this changed, and do they even work at all on space stations anymore?

**Comment by sayterdarkwynd** [comment]
they work fine. no change has been made that i know of.

**Comment by LycanBlackpaw** [comment]
I just went and tested it myself. I uninstalled every mod I had, left in ONLY FU, went through all the startup quests needed to get to a space station, went to that space station, placed one giant apiary with honeybees, and _even with a solar frame_, they don't work, as shown here: 
![20180611184104_1](https://user-images.githubusercontent.com/13260370/41262579-4fdbc97a-6da7-11e8-860f-fe03fcb39dad.jpg)

**Comment by LycanBlackpaw** [comment]
...Well I feel like a moron. I figured out why my bees weren't working, and it was actually really simple...I forgot to actually plant flowers in the room with the bees.
