### ISSUE TITLE
Addon for techstation patches

### ISSUE THREAD

**Issue by xn-5o8h** [sayterdarkwynd/FrackinUniverse#1424]
I guess you don't receive notifications on merged pull requests, so just in case: 
https://github.com/sayterdarkwynd/FrackinUniverse/pull/1420#issuecomment-396005957

> > Still, we should pack all of the stations in an addon that Includes all the race mods, and FU, so that we can make sure the SAIL works. but meh.
>
> Would this fit the bill? https://github.com/xn-5o8h/FUSAILModdedRaceSupport
> I can easily keep it maintained. It's only existing in that repo for now because I don't know if you want to have something specific going on with it and FU or whatever, waiting for your feedback.
>
> I could also make a PR to remove all the patches from FU, since having both seems unnecessary.

**Comment by sayterdarkwynd** [comment]
niiiiiice. I'll endorse this officially on the FU page.

**Comment by sayterdarkwynd** [comment]
And yea, if all the stuff is represented in the addon I see no issue with removing them from the main mod.
