### ISSUE TITLE
Field Generator does not protect from liquid nitrogen

### ISSUE THREAD

**Issue by Aussiemon** [sayterdarkwynd/FrackinUniverse#146]
The Field Generator's description says that it protects from all cold, but it does not prevent the "Deadly Chill" effect of liquid nitrogen. If adding this immunity would be overpowered, it seems like the description should be updated.

**Comment by renbear67** [comment]
I am sure that is not intended. We will address it ASAP. Thanks!

**Comment by sayterdarkwynd** [comment]
no, this is intended. it protects from environment effects, not liquids.

**Comment by renbear67** [comment]
Good to know.
