### ISSUE TITLE
StarboundItems

### ISSUE THREAD

**Issue by MarceloAlves** [sayterdarkwynd/FrackinUniverse#1460]
Hey there. I run the [StarboundItems] website (https://starbounditems.herokuapp.com/) ([marceloalves/starbounditems](https://github.com/marceloalves/starbounditems)). Over the past couple years I've had a lot of people ask me to put in the FrackinUniverse items but I never got around to it. Now I'm looking for new things to do with the website so I wanted to run the idea by you and make sure you're cool with it.

**Comment by sayterdarkwynd** [comment]
I'd prefer to not encourage cheating in FU.
