### ISSUE TITLE
Crewmembers [bug]

### ISSUE THREAD

**Issue by User353243** [sayterdarkwynd/FrackinUniverse#148]
Every crewmember is wearing a cap now. You cannot change this with a tailor.

**Comment by renbear67** [comment]
I can confirm. All my crewmembers are now wearing caps, whether or not they had headgear previously. It has overwritten anything else they were wearing.

**Comment by renbear67** [comment]
It appears that @sayterdarkwynd added new head and head-cosmetic slots to all crew members, and gave them the cap as a default. Perhaps we could leave the head slot empty by default? Does it generate an error if we do that?

**Comment by sayterdarkwynd** [comment]
the issue is that the TAILOR was supposed to be able to swap it. I need to add that in, then. Thanks.
