### ISSUE TITLE
Server crash on startup (Dedicated Server 64bit)

### ISSUE THREAD

**Issue by TheDevelon** [sayterdarkwynd/FrackinUniverse#1484]
Used the newest dedicated server (download over steam tools).

I had those other mods installed: https://i.imgur.com/cYZUXxd.png.

Stack trace on startup: https://imgur.com/dicscIQ.

I also tried to only use FrackinUniverse, same again with other mob type. (also reinstalled a few times)

Used FU version: 5.6.353 (newest)

Have a nice day,

TheDevelon.

**Comment by sayterdarkwynd** [comment]
I do not provide server setup support. I know absolutely nothing about starbound multiplayer.

Try speaking to the admins of the official FU server on our discord. shadow_absorber would know a lot more about this than I.
