### ISSUE TITLE
Thermal Shell

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#1559]
The thermal shell has the following tool tip: "Protects against deadly cold, heat, lava and fire. Grants 20% Ice and Fire resistance."

However...
```
function init()
  effect.addStatModifierGroup({
    {stat = "lavaImmunity", amount = 1},
    {stat = "fireStatusImmunity", amount = 1},
    {stat = "fireResistance", amount = 0.2},
    {stat = "iceResistance", amount = 0.2},
    {stat = "biomecoldImmunity", amount = 1},
    {stat = "biomeheatImmunity", amount = 1}
  })
  script.setUpdateDelta(0)
end

function update(dt)
end

function uninit()
end

```

It doesn't give deadlycold or heat immunity. only standard.

**Comment by sayterdarkwynd** [comment]
yes, this was because it now grants +20% resistance instead, so its less powerful in the new weather systems due to lava immunity being its thing. will change tooltip.

**Comment by Tamamo89** [comment]
sounds good...
