### ISSUE TITLE
Brewmaster NPC dies when initiating conversation

### ISSUE THREAD

**Issue by MrBlue12345** [sayterdarkwynd/FrackinUniverse#1560]
From the log file:

`[Error] Exception caught loading asset: /dialog/brewmaster.config:converse, (AssetException) Could not read JSON asset /dialog/brewmaster.config:converse`

`Caused by: (JsonParsingException) Cannot parse json file: /dialog/brewmaster.config`

`Caused by: (UnicodeException) Invalid UTF-8 code unit sequence in utf8Length`

The brewmaster.config file is encoded as ANSI.  Changing the encoding to UTF-8 and replacing the acented e and the ellipsis characters on lines 7 and 9 to their UTF equivalent appears to resolve the issue.

**Comment by sayterdarkwynd** [comment]
thx
