### ISSUE TITLE
Energy Packs

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#1562]
I forget why or even when these we're swapped but iirc the antimatter pack used to be the t4 energypack.

1) But the antimatter energy pack imho has one of the most difficult crafting trees. This is do to wretchel fruit being a part of it. (in other words, it's harder to acquire the ingredients then the quantum energy pack.) Getting all the stuff I needed for my antimatter pack... takes me an entire day. Buy at least i have the crafting tree memorized. Thankfully you can get them on strange seas. But those are incredibly dangerous.

2) That being said we should alter the recipes a bit. (keep the progression the same. erithian > protocyte > antimatter > quantum) Perhaps swap the focusing array and wretchel fruit, i don't know.

3) The quantum energy pack should also require aetherium alloy since its the best energy pack and is godly.

4) Lastly dense alloy which is tier... i forget should be swapped with advanced alloy for the dense alloy. In erithian energy pack. This way the player can get it sooner. I had everything for the proto pack by the time i crafted it.

Thoughts?

**Comment by sayterdarkwynd** [comment]
Im probably going to weaken every single one of them. They're all too good anyhow. But not bad as far as suggestions go.
