### ISSUE TITLE
Wand/Staff Glow Animation Alignment (minor)

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#1563]
[Visual Bug]
But some of these have their glow offset misaligned. The glowing orb when fully charged should be centered on the stone. I know the bone wand has this bug. And I'm going to check the others as well.
The question is do you wish for me to fix it?

**Comment by sayterdarkwynd** [comment]
yea, i didnt give them a full run, simple added the graphical layer. ive not had time to do much of anything, as I am not a full-time student in Game Design. Kinda taken my attention!
