### ISSUE TITLE
Mantizi Teleporter into a PGI

### ISSUE THREAD

**Issue by zimberzimber** [sayterdarkwynd/FrackinUniverse#1571]
Racializer attempts to use `/objects/ship/mantiziteleporter/teleportericon.png`, which doesn't exist because Mantizi have their name as the files prefix (`mantiziteleportericon.png`)

EDIT: Seems like the object is also trying to reference `teleportericon.png` in its directory, which doesn't exist for the same reason.

**Comment by sayterdarkwynd** [comment]
the issue is they are not supported by the racilizer yet

**Comment by zimberzimber** [comment]
Yes but there's also this part:
![image](https://user-images.githubusercontent.com/12485918/46802247-7ac63080-cd65-11e8-949e-268be49c59e4.png)

IDK if it applies to any other Mantizi objects
