### ISSUE TITLE
Suggestion: Planetary Rings?

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#1579]
Not sure if it's possible to scale down asteroid belts. But if it is. We could add planetary rings to gas giants?
Would you like me to see if it can be done?

**Comment by sayterdarkwynd** [comment]
i *think* they can be scaled. worth a try.

**Comment by Tamamo89** [comment]
@sayterdarkwynd 
I took a look at cockpitview.lua And it seems they are planets that have special rendering. If we add a 2nd asteroidbelt type which is a moon exclusive to gasgiants it _should_ work.
Do you want the rings to look like [this ](url
![image](https://user-images.githubusercontent.com/20710330/47020896-50c1a380-d195-11e8-8a5a-a0b09baf5ab4.png)
)or [this](https://i.ytimg.com/vi/SfbdrYev-v8/maxresdefault.jpg)?

**Comment by Tamamo89** [comment]
it doesn't... one slight issue. beam distance.
