### ISSUE TITLE
Ship fuel values?

### ISSUE THREAD

**Issue by moppr** [sayterdarkwynd/FrackinUniverse#1581]
In its current state, isotope (ship fuel) values for the amount of fuel they give looks like it could use rebalancing.

First, looking at the old vanilla items, Plutonium and Uranium, their ores give 6 and 7 fuel respectively, and the rods give 21 and 25 fuel. Considering their availability and low fuel needs in general, these are reasonable values.
However, the two mineables in FU, Neptunium and Thorium, have oddly low values (4/4 for the ores and 5/6 for the rods). If they're intended to be more rare and valuable than the other isotopes, these fuel values don't reflect so at all. Taking into consideration that they're slightly less common than the vanilla items, it would make more sense for each rod to give in the 30-50 range. Side note, it seems backwards that Neptunium is listed as rare and Thorium as uncommon, when the latter has a higher pixel value and seems to spawn on higher tier planets.
What's really odd, however, are the manufactured isotopes. Deuterium only gives 2 fuel per rod, and Tritium only gives 3. For the effort needed to obtain decent quantities of either, this is pitifully low. And then out of nowhere, Ultronium gives 300 fuel per rod. What? The progression could afford to be much more linear up to this point.

**Comment by Tamamo89** [comment]
Yeah this is incorrect.
I'm gonna go over all the fuel amounts give me a sec.

**Comment by sayterdarkwynd** [comment]
they are fine, and currently as intended.
