### ISSUE TITLE
Machines stay on with leftovers

### ISSUE THREAD

**Issue by gamrguy** [sayterdarkwynd/FrackinUniverse#159]
If leftovers (less than required amount of a processable material) are left in a machine, the machine will continue to be on and consume power, even though the machine is no longer actually processing anything.

To replicate: Place any amount of processable material into a powered machine that processes in groups that is less than the required amount (e.g. one ore in a blast furnace, 1-2 liquid in a centrifuge). The machine will appear to be on and will consume power while not doing anything.

**Comment by renbear67** [comment]
Fixed in pull request #160
