### ISSUE TITLE
Xeno Research Lab: No support for "Flesh Fragment" seeds or "Mushroom Seed"?

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#165]
The Xeno Research Lab does not know what to do with "Flesh Fragment", which are the seeds for a plant that grows in underground Flesh mini biomes. (It can be grown as a crop and harvested for Flesh Strands.) Lack of support is strange, considering that this is a Frackin Universe crop. (See "fleshseed.object" in your objects\farmables\fresh.) This is an oversight, right? I find it hard to believe that it would be intentional.

Also, the Xeno Research Lab does not support the Mushroom Seed.
http://starbounder.org/Mushroom_Seed
Granted, in vanilla Starbound there's no way to obtain it. But it -is- found in the vanilla files. And there's at least one mod which allow Mushrooms to grow from seeds - namely, Craftable Seeds.

**Comment by sayterdarkwynd** [comment]
and does craftable seeds have anything to do with FU? Nope. So fuck bothering to code in seeds I have no use for. 

the flesh thing is an oversight though, thanks
