### ISSUE TITLE
Missing mask on Siren's Helm

### ISSUE THREAD

**Issue by Silverfeelin** [sayterdarkwynd/FrackinUniverse#1653]
The Siren's Helm item defines a `mask.png`, but the asset itself isn't present. I assume the game handles this and uses `/assetmissing.png` behind the scenes, but when rendering the item externally (i.e. on a canvas) this logs the below error.
```
[19:08:32.166] [Error] Could not load image asset '/items/armors/tier3/siren/mask.png', using placeholder default.
(AssetException) No such asset '/items/armors/tier3/siren/mask.png'
```
If this is not seen as a problem that should be addressed, feel free to close the issue.

Asset: https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/items/armors/tier3/siren/kinumoarmor.head
Related issue: https://github.com/Silverfeelin/Starbound-Wardrobe-Addons/issues/17

**Comment by sayterdarkwynd** [comment]
thx
