### ISSUE TITLE
apexhoverbike issue

### ISSUE THREAD

**Issue by AllenWorker** [sayterdarkwynd/FrackinUniverse#1664]
https://github.com/sayterdarkwynd/FrackinUniverse/blob/a48ffce59c62070f5725d28329c2211b0b0ceb34/vehicles/apexhoverbike/apexhoverbike.animation#L203

I think ".png" is missing.
it will encounter an Error "[Error] Could not load image asset '/vehicles/apexhoverbike/apexhoverbikeforeground', using placeholder default.
(AssetException) No such asset '/vehicles/apexhoverbike/apexhoverbikeforeground'"
because it's trying to look for "apexhoverbikeforeground" not "apexhoverbikeforeground.png"

**Comment by sayterdarkwynd** [comment]
thanks. super easy fix.
