### ISSUE TITLE
Can you optimize all PNG?

### ISSUE THREAD

**Issue by DartPower** [sayterdarkwynd/FrackinUniverse#1682]
Can you optimize all PNG?
Using the ImgBot for Github (https://imgbot.net) or... exotic variant like "DOOM-Crusher" toolset (https://github.com/Kroc/DOOM-Crusher)
This saves the size and makes better performance.

**Comment by DartPower** [comment]
ImgBot is good thing
But DOOM-Crusher also
![image](https://user-images.githubusercontent.com/2005369/51437807-46430880-1cb4-11e9-95f3-c140f16d289a.png)

**Comment by sayterdarkwynd** [comment]
We optimize pngs regularly, actually. This is a needless request. 

Every few months, I run stuff through PNGauntlet.
