### ISSUE TITLE
A way to disable the races Frackin Universe adds?

### ISSUE THREAD

**Issue by chexo3** [sayterdarkwynd/FrackinUniverse#1727]
I don't care for them, I can deal with having them in the universe, but I don't want to have them show up in my character creator. Is there a way to do this?

**Comment by sayterdarkwynd** [comment]
Simply don't use them. I'm not patching them out.

**Comment by chexo3** [comment]
They feel tacked on, and I don't want to use a character extender to be able to play. I basically just want to make an extender that doesn't actually add slots for them, or adds invisible offscreen slots.
