### ISSUE TITLE
Suggestion: Martinus Transformer as craftable object

### ISSUE THREAD

**Issue by meekstone** [sayterdarkwynd/FrackinUniverse#173]
I would love to see a "Martinus Transformer" as a craftable object that very slowly converts water into any other liquid, as long as you supply some starting amount of the second liquid. (Basically a box with two input slots and one output slot.)
The Martinus Transformation (see http://community.playstarbound.com/threads/infinite-fuel-the-martinus-transformation.91928/) still works (with any liquid) but it's always quite time (and space) consuming to build one. Having an expensive craftable object instead would really be nice. It could also require a lot of power to make it more demanding to operate.
Thanks for the tremendous amount of content you already created!

**Comment by sayterdarkwynd** [comment]
well, I think this would be imbalanced as shit without careful implementation. Infinite of certain liquids is insanely good (protocite anyone!??!)

that said, its useful for other liquids and I don't see why we *Couldn't* do it. But could does not mean should. 

Worth a go, as an experiment, when we have downtime.
