### ISSUE TITLE
New Mechs bugs

### ISSUE THREAD

**Issue by Stroud1227** [sayterdarkwynd/FrackinUniverse#1731]
Love the new mech system! 

But using the oil refinery to change oil to unrefined mech fuel gave me generic item. I put the liquid files from the original mod ( /liquids/mechfueltex.png   and   /liquids/mechfuel.liquid ) into the frackin folder and it fixed this. 

There is also something going on with fueling the mech all the way to max. For me right now it only goes to 500/825 max fuel, takes the extra fuel it would need to get to 825, then stays at 500. I guess a math error somewhere, I tried looking around but could not figure it out lol

**Comment by sayterdarkwynd** [comment]
I will not be adding the liquid file, period. FU does not need more liquids. The liquid Item is fine though. I'll investigate that.

as for the math: i havent noticed the problem. I'll have to peruse that too.

**Comment by Stroud1227** [comment]
The exact parts I was using to test the fuel:

Falcon Body, Stock Mech Boosters, Flak Cannon Mech Arm, Drill Mech Arm, Stock Mech legs, Energy Field I

If that helps pinpoint it at all.
Thanks!

**Comment by sayterdarkwynd** [comment]
Yea, it seems to not want to max-fill. 

I suspect its because the maxFuel value is being recomputed elsewhere, for one part of the calculation, ignoring the "bonuses" i added after the fact.

**Comment by sayterdarkwynd** [comment]
allright fixed it!

**Comment by Stroud1227** [comment]
Sure did! thanks again!
