### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Klebestreifen** [sayterdarkwynd/FrackinUniverse#1740]
My game crashed during launch.
[my starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/2873121/starbound.log)

I only installed FU-5.6.2862. According to Steam, my game is flawless.

My OS: Win7 x64
My SB Version: 1.3.4

**Comment by Klebestreifen** [comment]
With Win32 Assembly: 
[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/2873253/starbound.log)

**Comment by sayterdarkwynd** [comment]
You did not read the main FU page on CF or Steam: You MUST have a character extender installed.
