### ISSUE TITLE
Workshop Page????

### ISSUE THREAD

**Issue by ProjectSky** [sayterdarkwynd/FrackinUniverse#1746]
![image](https://user-images.githubusercontent.com/16351827/53015954-4424c300-3487-11e9-887c-103f02ab26d9.png)

* It is gone?

**Comment by MokahTGS** [comment]
Um, yeah I'd like to know that as well...

**Comment by MokahTGS** [comment]
Looks like there was a copyright claim that was issued and resolved, but the file got taken down anyway.

**Comment by sayterdarkwynd** [comment]
automated steam process. sucks. Literally no human was involved. Claim goes in. litigate-bot disables account. says "yuo can counter-file". So we did. "you counter filed. we'll add your stuff back in 14 days"...

but a human could have taken one look and seen we were in compliance and avoided it all. *shrug*
