### ISSUE TITLE
Unable to read all of the FR stat popups in character creation

### ISSUE THREAD

**Issue by JadianRadiator** [sayterdarkwynd/FrackinUniverse#1813]
I need to report a qol issue with FU/FR character creation screen.
The pop-up stats window is off-set explicitly from your mouse cursor.
Which unfortunately means that significant portions of ___ race's stats popup gets cut off.
[These](https://steamcommunity.com/sharedfiles/filedetails/?id=1733353014) are the mods I am using.
And [here](https://imgur.com/a/q2WhwQS) are my example screenshots.
P.S. I am using a tv as a monitor to extend my pc's screen space.
The screen and resolution shown are from my laptop's built-in monitor at it's maximum size.
Rezing the window to make them fit,
makes everything too small to read.
Doing full-screen mode with a smaller resolution,
reduces the game-play's quality.

**Comment by sayterdarkwynd** [comment]
Why are you reporting this on FU? This is FR.

even so: this is entirely due to your resolution and there is literally nothing I can do about it because starbound does not let me change that screen via API

**Comment by JadianRadiator** [comment]
So I'm screwed and will never be able to see the whole pop-up?
It's more about the way Starbound scales the gui than it is about the resolution in and of its self.
Do you know if there's a mod that'll let me change the way Starbound scales gui's?
