### ISSUE TITLE
Duplicated Material id 

### ISSUE THREAD

**Issue by XSiromaX** [sayterdarkwynd/FrackinUniverse#1857]
hi i found something
[Error] Application: exception thrown, shutting down: (ObjectException) Error loading object '/objects/critters/mod/mcm/fubrownsnake/crittercage.object': (MaterialException) Error loading material file /tiles/materials/skath/skathwallbeams.material
Caused by: (MaterialException) Duplicate material id 8009 found for material skathwallbeams

**Comment by sayterdarkwynd** [comment]
uninstall luxury tiles
