### ISSUE TITLE
what would i need to include in an addon to avoid legal issues

### ISSUE THREAD

**Issue by Vortetty** [sayterdarkwynd/FrackinUniverse#1874]
just wondering what i would have to include in an addon to distribute it without any legal issues happening due to me distributing modified code, or is this open source?

the addon i am planning to make will add the ability to jump when using the spider sphere, and what was changed in the spider sphere code to make you unable to jump, is it something with gravity finding?

**Comment by sayterdarkwynd** [comment]
Simply put: dont touch art assets. 

Make your mod require FU as a dependency and you can reference the art directly then.

As for the coding bit: this git is not a place to get a tutorial on how to write it. I don't have the time nor inclination to do so.

**Comment by Vortetty** [comment]
Ok! Thank you! The coding bit was more I was just wondering what you changed to make the sphere climb on walls other than the gravity engine for when you hev that sphere
