### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by MrPug1** [sayterdarkwynd/FrackinUniverse#1915]
the only mods I have are FU FR and xbawks extender and it crashes on launch
[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/3485064/starbound.log)

**Comment by sayterdarkwynd** [comment]
[23:33:56.410] [Error] Application: exception thrown, shutting down: (ItemException) Duplicate item name 'xibulb' found


you have something installed twice, or something else interfering.
