### ISSUE TITLE
Huge amount of lag due to Item Network

### ISSUE THREAD

**Issue by Xaymar** [sayterdarkwynd/FrackinUniverse#1928]
I've been trying out the Item Network in Frackin Universe, and have been successful at creating small and even large networks. But there is an insane amount of lag wherever an Item Network is created that in some cases seems to loop.

Any advice on how to fix this, or is this just completely unusable for anything on a larger scale?

**Comment by Xaymar** [comment]
The problem seems to be ITDs, as they aren't "one-way", at least they don't behave like that. The following room, when disconnected from the network, will remove all lag:

![image](https://user-images.githubusercontent.com/437395/63488000-a3eb3d80-c4ad-11e9-948a-60657e31a794.png)

The problem appears as soon as I reconnect the ITD to the network. It's set to only pull Food and Prepared Food items.

**Comment by Xaymar** [comment]
Is it possible that the cause of the lag is due to the cyclic nature of my network? My networks are set up so that both input and output are connected to each repeater, so two repeaters essentially create a loop.

**Comment by sayterdarkwynd** [comment]
The lag is fine if you dont overdo it.

There is a memory leak in the 64bit client that exacerbates the issue a *lot*. to the point where you'll be using a gig of ram within moments if you overdo it.

**Comment by Xaymar** [comment]
How is 15 seconds of lag _fine_?

**Comment by Xaymar** [comment]
> Also, why are you connecting repeaters to one another? That's obviously part of the issue.

Because otherwise there's no way to make a connected network that is accessible from all points.
