### ISSUE TITLE
FU liquid/material interactions cause poison trap in Floran mission to dry out

### ISSUE THREAD

**Issue by renbear67** [sayterdarkwynd/FrackinUniverse#195]
Basically, the poison + dirt (I think) = sewage interaction causes all the poison in the poison trap in the floran story mission to be converted to sewage, thereby making the trap effectively inert. I strongly recommend either disabling the interaction, editing/overriding the Floran mission (completely beyond my abilities, BTW), or finding some way of stopping the interaction for that mission only.

**Comment by Tamamo89** [comment]
Would it be possible to create a new material, and edit the dungeon file so that is use instead of dirt @renbear67

**Comment by renbear67** [comment]
That's a thought, but I seem to remember we've been avoiding editing any of the vanilla missions. I'd hate to start now.

**Comment by renbear67** [comment]
I should amend this to say I can think of at least two poison traps that are severely affected by this interaction, and one that is mildly so.

**Comment by Tamamo89** [comment]
@renbear67 
True it would be best not edit the vanilla mission. Does poison effect mud?
We could just it so poison + mud = sewage. There is no mud in the Floran Mission, I just checked.
