### ISSUE TITLE
Translocator vanishes from inventory in first quest cavern

### ISSUE THREAD

**Issue by scottmudge** [sayterdarkwynd/FrackinUniverse#1961]
Just playing through on a clean 1.4.4 install w/ FrackinUniverse.

During the first quest line where the player must go through the cavern in search of the power source, the translocator from my inventory vanished. I had to spawn a new one using the admin commands. 

Why would it have vanished? Is the rest of my saved game bugged?

**Comment by sayterdarkwynd** [comment]
nothing would make it do so.
how did you even have one that early in the game?

sorry, no idea man.
