### ISSUE TITLE
[Suggestion] use git lfs

### ISSUE THREAD

**Issue by Jan200101** [sayterdarkwynd/FrackinUniverse#2080]
the size of the repo alone makes some people unable to clone it, using git lfs would solve that problem

**Comment by sayterdarkwynd** [comment]
I have no idea what that even is.

**Comment by Jan200101** [comment]
git lfs is an open source extension to git that aims to support versioning of larger files, something git is inherently bad at
https://github.com/git-lfs/git-lfs

**Comment by sayterdarkwynd** [comment]
Not really a major concern for us either way. Cloning the repo solves that issue forever, since you can just do a git pull, at that point.
