### ISSUE TITLE
Huge generation lag on the bottom of aether sea

### ISSUE THREAD

**Issue by IronX5000** [sayterdarkwynd/FrackinUniverse#2099]
I have no idea why but when I try to reach the bottom of the aether sea to mine ores the generation utterly slow down to a crawl and I have to wait for each chunk to generate one by one as everything around me become laggy (monsters barely move, which is weird become the lag doesn't affect my character).

When I finally reach the ground, I found that, apparently, the entire sea is generated on top of some chunk of air so the entire sea is falling down which could be the reason why the generation lag so much (It's maybe something else but I saw aether filling up empty spots as I arrived which means air was generated here).

Once I dug deep enough the lags stopped.

It's kind of a real problem because it can sometimes take 10 - 15 minutes to reach the bottom of the sea. This isn't normal, this wasn't a problem in earlier versions and I know it's not from my side.

**Comment by sayterdarkwynd** [comment]
welcome to starbound. 

Nothing has changed in Aether Seas that would cause an increase in lag. Sounds like a system-specific issue. 

As for the ocean itself generating weird: sometimes that happens, specifically on worlds larger than a certain threshold, with oceans. It's always happened, and we suspect thats why vanilla oceans are never on large worlds. We've found no reason for it to occur.
