### ISSUE TITLE
Shellguard gun staff "sgpraxisimperium" still break after upgrade via crucible

### ISSUE THREAD

**Issue by adaxe** [sayterdarkwynd/FrackinUniverse#2170]
Hi satyer,

I just tried upgrade praxis imperium via crucible, and found that fireTime and baseDPS were still written into its primaryAbility and thus break the weapon, like shown in the log : https://pastebin.com/VHMhh1Jy

There might still be something wrong with the condition on line 195 & line 263 of interface/scripted/weaponupgrade2/weaponupgrade2gui.lua.

I am sorry that I cannot give any useful suggestions as I am really confused with "or" operation in .lua and not quite understand how starbound handle categories.

**Comment by sayterdarkwynd** [comment]
I don't honestly care either way, since it in no way has to do with vanilla nor FU Good attempt thoug, at the fix! You tried, at least. I'll have to peek at it another time.
