### ISSUE TITLE
An online problem, or world gen problem

### ISSUE THREAD

**Issue by ThiagoRiolu** [sayterdarkwynd/FrackinUniverse#2208]
I was playing online with a friend yesterday and when i warped down to a planet i got the following error and got disconnected: "[Error] Exception caught in client main-loop
(ObjectException) No such object named 'wildselvasseed'". We both only have Frackin Universe, please help.

**Comment by sayterdarkwynd** [comment]
Neither. That is not a plant in frackin universe. The only reference to it is in the extraction recipes, which cannot cause an error in the way you are experiencing. Sorry, this is not related to FU. Rather, to something that has been removed that is being looked for, which exists on worlds that already exist.
