### ISSUE TITLE
Harvester Beamgun tilts Hydroponic Tubing tiles incorrectly

### ISSUE THREAD

**Issue by edwardspec** [sayterdarkwynd/FrackinUniverse#2278]
When used on Hydroponic Tubing, right-click ability of Harvester Beamgun (that tilts and waters targeted tiles) tilts it as normal soil (unlike when tilting it by hand), meaning the plants won't grow on it unless explicitly watered.

**Comment by sayterdarkwynd** [comment]
not an issue we can really do anything much about without recoding the device. Its been a minor thing for ages, and not really worth the change.

**Comment by edwardspec** [comment]
It is possible to modify the tooltip of Harvester Beamgun?
Something like
```
Left-click: quick harvest of crops/flowers/trees.
Right-click: tilt soil (except Hydroponic/Aeroponic tiles)
```
would probably prevent players from running into this.

**Comment by sayterdarkwynd** [comment]
thats probably the simplest solution.
