### ISSUE TITLE
Replacing old bee queen with adult (non-young) queen makes new bee queen as old as the previous queen

### ISSUE THREAD

**Issue by edwardspec** [sayterdarkwynd/FrackinUniverse#2279]
Steps to reproduce:
1) Have a bee queen with red "time remaining in service" bar in the Apiary's queen slot.
2) Place another adult bee queen (not young queen) with green/yellow bar into this slot (replacing the old queen).

New queen will also have the red bar (instantly becoming old), even if she had green/yellow bar before.

This only happens if the old queen is replaced directly. It doesn't happen if the old queen is removed first, and then new queen is placed into the empty slot. Young queens are also unaffected.

**Comment by sayterdarkwynd** [comment]
thanks. we'll peek.
