### ISSUE TITLE
Filtering all bee queens in Item Transference Device

### ISSUE THREAD

**Issue by edwardspec** [sayterdarkwynd/FrackinUniverse#2282]
Is it possible to make bee queens into their own separate type other than "Crafting Material"?

Usecase (this is probably very common): young queens are automatically moved (via Item Transference Device) to one place (in simplest setup - the chest near Advanced Microscopes), and all other output is moved to main storage chests.

Current workaround is to place 1 young queen of each species into Exact filters of Item Transference Device.
This works, but has drawbacks (limited to 5 bee species per device, needs to be reconfigured every time one bee species is replaced by another, can be super costly on early stages of breeding a new species - when it has Queen Breeding Rate of 1 and you just can't spare 2 young queens of this type as "examples" for Item Transference Device).

**Comment by sayterdarkwynd** [comment]
No, nor will we be doing this. Bees are not intended to be automated.
