### ISSUE TITLE
Possible inconsistency in beeData.config? (plasterer bees)

### ISSUE THREAD

**Issue by edwardspec** [sayterdarkwynd/FrackinUniverse#2283]
I've been looking at `bees/beeData.config` and found something odd.
1) "production" config of "plasterer" bees is completely identical to "cybernetic" bees (copy-paste typo?). For example. they produce "liquidoil".
2) However, this typo has no effect on the game - Plasterer bees produce Pure Honey, not "liquidoil".

https://github.com/sayterdarkwynd/FrackinUniverse/blob/79524a52239f7c3c1a2ca26eeef2a323a5b1ba78/bees/beeData.config#L285-L297

**Comment by kukagres** [comment]
I think you are seeing outdated code from about 4 months ago.

**Comment by edwardspec** [comment]
Sorry, my bad.
