### ISSUE TITLE
[BYOS] Can't hire crew

### ISSUE THREAD

**Issue by Bimbo-Bungus** [sayterdarkwynd/FrackinUniverse#2341]
I recently started a new game as an Avikan and chose to build my own ship. At the time, I did not have the Official FU BYOS Modded Race Patch for FR Supported Races installed. When trying to hire other Avikan crew members, I could not, despite having multiple valid rooms. By then, I DID have the BYOS Modded Race Patch installed. Two screen captures and the starbound.log file are included.

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/5071497/starbound.log)

![ProblemArea](https://user-images.githubusercontent.com/69026073/90188466-5b88f780-dd70-11ea-8f6f-e40cf58d8d3b.png)
![CrewCandidates](https://user-images.githubusercontent.com/69026073/90188483-62b00580-dd70-11ea-854d-d7757acaa195.png)

**Comment by sayterdarkwynd** [comment]
Youre playing a modded race. You shouldn't be using the FR version at all unless you are only using FR. It won't work otherwise.
