### ISSUE TITLE
Electricity isn`t working

### ISSUE THREAD

**Issue by So1d13r** [sayterdarkwynd/FrackinUniverse#2350]
![unknown](https://user-images.githubusercontent.com/70152559/91060424-983bd500-e633-11ea-8c49-cc9ce419fca4.png)
Simple circuit. 4W nocturn array and 6W EMPTY battery. And that`s enough to power up 10W powder sifter AND to charge battery (through the output). And the more batteries connected, the more power output and the more free energy. Looks like batteries outputs works bad and they could power up themselves. Works with any batteries/generators and dont without any generators connected.

**Comment by sayterdarkwynd** [comment]
thats the idea. You need a generator connected. battery issue is known, but not a problem. doesnt impact performance.

**Comment by So1d13r** [comment]
> thats the idea. You need a generator connected. battery issue is known, but not a problem. doesnt impact performance.

Whaaat? "The idea"? Thats an energy from nothing. Totally ruined all the electric system. And problem NOT with the only batteries, by the way. Most stations could be powered through outputs. I could power up most of station using the only few solar panels and thats not a problem?... =\
