### ISSUE TITLE
Visual glithch

### ISSUE THREAD

**Issue by Doodlinka** [sayterdarkwynd/FrackinUniverse#2393]
Thick Layered Ice dissapears when painted. Log and video included.
Edit: Jagged Ice, Deep Frozen Ice and Frozen Stone have the same issue, but vanilla ices do not.

[Starbound 2020-09-18 18-57-53.zip](https://github.com/sayterdarkwynd/FrackinUniverse/files/5246689/Starbound.2020-09-18.18-57-53.zip)
[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/5246674/starbound.log)

**Comment by sayterdarkwynd** [comment]
They are not intended to be dyed.

**Comment by Doodlinka** [comment]
if they shouldn't be painted, make them not change color instead of causing a visual glitch
