### ISSUE TITLE
A miniboss spawned in the hylotl mission

### ISSUE THREAD

**Issue by Doodlinka** [sayterdarkwynd/FrackinUniverse#2400]
i was teleporting around, which also caused some large fish to spawn in unintended places (i.e. a room that was being drained)
apparently i went far enough to cause this to spawn inside a room
![image](https://user-images.githubusercontent.com/62027005/93687958-e3c68f00-faca-11ea-90b4-4ae4d5b9c41a.png)

**Comment by sayterdarkwynd** [comment]
How is this an issue? It is 100% on purpose and part of the mission now.

**Comment by Doodlinka** [comment]
Oh, sorry. I see that you changed vanilla missions, but this made no sense to me, because how did it even get here? By "on purpose" do you mean you put it here or you allowed it to spawn in any flooded room?
