### ISSUE TITLE
Unknown biomes should load a random status effect from a pool

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#248]
applying an effect completely at random (from a list of various harmful and beneficial ones) would be really fun. 

Imagine a world where every NPC has the Thorns effect? Or one in which there is reverse gravity? etc

**Comment by Tamamo89** [comment]
@sayterdarkwynd 
Strange seas as well perhaps?

**Comment by aztectornado** [comment]
Shadow worlds too?
