### ISSUE TITLE
FrackinRaces: melee combo buffs not unstacking

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#254]
long story short, when a character using the melee-combo ability gains the buffs, they do not vanish as expected after being hit or completing the combo.

This is most easily seen on a Glitch character.

The desired behavior is   
attack combo --> get bonus
finish combo or get hit -> lose bonus

currently, when the glitch attacks he gets the defense bonus....and then it stays, which really fucks up stat balance through the entire game (as it is around +9 always, which is +6 above what it ought to be )  (rockin a 91 defense while in War Angel before any other buffs.... damn)

**Comment by renbear67** [comment]
Should be fixed now after the pull request. (Different repo, so I can't directly refer.)
