### ISSUE TITLE
Imperius Minigun - special script fix needed

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#256]
as it uses energy, it fires faster. However, this has the unintended side-effect of its damage lowering. This should be corrected so that it does the same damage across the board, rather than reducing

**Comment by NotMrFlibble** [comment]
Should this be damage only, or should it also use energy faster?

**Comment by sayterdarkwynd** [comment]
energy rate is fine. damage simply needs to stay stable rather than adjust for energy used by the default engine code. makes it rather pointless otherwise
