### ISSUE TITLE
is it possible to make crew members resistant to effects?

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#264]

**Comment by IrisBlanche** [comment]
In the player config there are 2 script parts. One for player (which you're using for FR) and one for the companions. Maybe you can use this and add a new script to assign specialized immunity effects to the crew members.

**Comment by sayterdarkwynd** [comment]
Thats fine if I want them all to have the same immunities. Not so much for when I don't. I can do it in various ways, but none are ideal just yet.

**Comment by IrisBlanche** [comment]
I don't know if it possible to get the profession of the crewmember inside the script but if it's possible you could add the statuseffect by doing something like "fu_" .. profession .. "_crewstatus" or something like that if you want to have it set by their profession.
