### ISSUE TITLE
Issue with mechs

### ISSUE THREAD

**Issue by autismusprime69** [sayterdarkwynd/FrackinUniverse#2643]
I am new to Frackin Universe. I just recently completed the "Test Drive" quest that is supposed to unlock mechs. But for some reason, that is not happening. Whenever I open the mech assembly table, I am given the "configuration incomplete" message. I did the modded version of the quest, so I do not know if I am doing something wrong. I tried uninstalling and reinstalling the mod, but it did not work. Am I doing something wrong?

(I am currently unable to include a starbound.log file, as I currently do not know how to do so at the moment. If pc specs are to do with the bug, then I am playing on a Dell G7 15)

**Comment by sayterdarkwynd** [comment]
this is not a bug. You did not read the quest text, at all.

It -explicitly- states that you need to research the mech yourself and -craft- it , and gives you nearly all the materials to do so.

**Comment by autismusprime69** [comment]
Thank you.
