### ISSUE TITLE
BYOS's bug of character before research system update

### ISSUE THREAD

**Issue by drowsc089** [sayterdarkwynd/FrackinUniverse#2676]
SAIL implied 'Constructing ship's SYSTEM/SAIL'（cant remember the message details)

I cant start a mission or dimiss my crew memeber  etc. now 
All the jobs SAIL can do is malfunction. 
How to solve that ?

**Comment by drowsc089** [comment]
btw,after the Release 6.0.161

**Comment by drowsc089** [comment]
new character is totally fine

**Comment by sayterdarkwynd** [comment]
/entityeval world.setProperty("fu_byos", true)" while in admin mode with your cursor over an object
