### ISSUE TITLE
Top tier elder crafting tables do not drop when broken

### ISSUE THREAD

**Issue by Kyuuketsuki** [sayterdarkwynd/FrackinUniverse#2742]
Speaking specifically of objects elderbookstand and elderscrolldesk. Their prior stages do drop when broken, so I assume this is not expected behaviour.

I don't see where to set this normally, or I would post a PR. Sorry about that.

**Comment by sayterdarkwynd** [comment]
intentional.

**Comment by Kyuuketsuki** [comment]
If intentional, probably should be stated somewhere. I could be bad and missed it somehow, though.
