### ISSUE TITLE
Irrigation - possible to do?

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#275]
Obviously would be somewhat complex. However, various mods exist that allow movement of liquid via pipes and so forth. 

So I guess the question really, is how best to do this and make it interesting (and desirable) to a player to do this?

Could we perhaps do a similar thing to what Bees! does, and have random chance of bugs eating your crops? Would give more purpose to Fertilizer. And the better irrigation you have set up, the less chance of pests eating your veggies (especially when paired with fertilizer) ?

Any other ideas?

Might be worth exploring eventually.

**Comment by thaelina** [comment]
Something like this?
http://community.playstarbound.com/resources/automatic-irrigator.3127/

**Comment by sayterdarkwynd** [comment]
no, not at all what I was thinking but would actually do the trick nicely.

**Comment by thaelina** [comment]
Ahh well you mentioned irrigation and its an old mod I used to use. At
least its part of the request I guess

**Comment by sayterdarkwynd** [comment]
it seems a good way to handle it, actually. water to pipes, pipes to plants. easy to understand for everyone
