### ISSUE TITLE
Vanilla weather projectiles are gone or renamed as of 1.1.1

### ISSUE THREAD

**Issue by renbear67** [sayterdarkwynd/FrackinUniverse#276]
No more `sandstormslow.projectile`, for example. If we *have* to, we can copy the vanilla asset. We can do that if 1.1.1 goes Stable before this issue is closed. But I would ideally like to convert our weather to the new system.
If there **is** a new system, heh. I think they may have moved to a "ray" system rather than projectiles, but they might have just renamed things. I haven't started digging, other than to identify the problem.

**Comment by renbear67** [comment]
Oh, it's not even that. Weather effects are **ambient** now.
Previously, from `sandstorm.weather`:
```JSON
    {
      "projectile" : "sandstormslow",
      "parameters" : {
        "power" : 0
      },
      "velocity" : [0, -100],
      "ratePerX" : 0.1,
      "spawnAboveRegion" : 30,
      "spawnHorizontalPad" : 10,
      "windAffectAmount" : 1
    }
```
Now:
```JSON
  "statusEffects" : ["sandstorm"],
```

**Comment by renbear67** [comment]
`sandstormslow` is now replaced in all weather files it appeared. There may be others that have been removed in vanilla, and will need to be taken care of before the Stable push.

Interestingly, several other weather statusEffect projectiles are still in the assets, most notably the rain/lightrain projectiles.

**Comment by sayterdarkwynd** [comment]
we should apply the same to the "wet" effect and poison rain


additoinally, FU tar rain, sulphuric weather and others should probably swap to statusEffect as well

**Comment by renbear67** [comment]
I don't think we can do tar rain, since it's a deposit-liquid thing, right? The statusEffect stuff is only for things that make sense as just an invisible ambient thing, IMO. Hence rain and lightrain still being projectiles. I'll see if there's an ambient wet effect being used in vanilla weather, though.

I'll look at sulphuric weather and the others.

Another example of invisible-ambient would be, like, a solar storm that gives ffextremeradiation for its duration.

**Comment by renbear67** [comment]
Interesting. `junkstorm.weather`, a vanilla weather, has no `"projectiles" :` section at all. Apparently it's not required, then.

**Comment by renbear67** [comment]
For the record, I misremembered the names of the rain projectiles. They are `water` and `lightwater`.

**Comment by sayterdarkwynd** [comment]
yes. And I think exceptions need to exist, too. For instance, Sulphuric planets are not threatening once you have the protection. So making the rain apply *poison* rather than straight sulphuric effect can shake things up as well. In those cases, the rain would need a projectile (as you mention with tar rain as an exception as well). Proto blobs, lava blobs and a few others do exist. Organic soup rain can be made into invisible liquid like normal rain. Grav rain is already like that, i think...if not, it too should be.
