### ISSUE TITLE
Metaphysics skill tree

### ISSUE THREAD

**Issue by Frex666** [sayterdarkwynd/FrackinUniverse#2764]
Hi there,
I'm currently enjoying the mod and content put out by you guys and appreciate it. I've been looking at the metaphysics but the skill tree isn't open and as far as I know, it should be. I was wondering what I need to do as there is nothing but open up the skill tree branches and it isn't there. I have over 200 madness so I'm wondering if I have encountered a bug or I'm just being stupid. Sorry for the bother.

**Comment by sayterdarkwynd** [comment]
It automatically is revealed to you after completing Esthers "scan shit at the outpost" mission.
