### ISSUE TITLE
Organic Soup Lua needs a wholesale revamp

### ISSUE THREAD

**Issue by renbear67** [sayterdarkwynd/FrackinUniverse#279]
It *cries out* for a rewrite. It makes no sense. For example:
```Lua
  if (status.resourceMax("health")) * _x >= 100.0 then
     effect.addStatModifierGroup({{stat = "maxHealth", amount = baseValue }})
     else
     effect.addStatModifierGroup({{stat = "maxHealth", amount = baseValue }})
  end
```
Wut.

**Comment by NotMrFlibble** [comment]
Ditto
```
stats/effects/percentenergyboost/percentenergyboost.lua
stats/effects/percenthealthboost/percenthealthboost.lua
stats/effects/fu_tileeffects/contaminatedpoison/contaminatedpoison.lua
stats/effects/fu_tileeffects/biooozepoison/biooozepoison.lua
stats/effects/fu_tileeffects/pus/puseffect.lua
stats/effects/fu_tileeffects/mercurypoison/mercurypoison.lua
```

**Comment by sayterdarkwynd** [comment]
all my fault. I kept meaning to go back to them and kept putting it off :)

**Comment by renbear67** [comment]
Understood. So what did you want it to do? That's probably a good place to start. A reminder: This is the buff you get from touching Organic Soup. Well, the one I mentioned at first is. We can talk about the others separately.

(Not what it DOES, what you WANTED it to do.)

**Comment by sayterdarkwynd** [comment]
Well, im open to suggestions. At this point something "unique" would be a good idea there. I don't even remember what it DOES do right now other than a buff to HP or some shit like that.

Healing Water does healing already.
I think proto liquid does energy healing (correct if i am wrong)

so healing is taken care of. Why don't we make organic soup reduce hunger? The longer you stay in the more full your hunger bar gets? Thats useful and *nothing* does that in the entire game other than food.

**Comment by azah** [comment]
Something like this? 
```lua
  hungerLevel = status.resource("food")
  hungerMax = status.resourceMax("food") -- 70

  if (hungerLevel < hungerMax) then
    adjustedHunger = hungerLevel + 0.2 -- decent rate, not too fast
    status.setResource("food", adjustedHunger)
  end
```

**Comment by sayterdarkwynd** [comment]
that might just do the trick. ill test it.

**Comment by NotMrFlibble** [comment]
Unfortunately, that use of status.resourceMax("food") in the orgainc soup script is causing a lot of exceptions:
`Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/stats/effects/fu_tileeffects/organicsoupeffe..."]:21: (StatusException) No such resource 'food' in StatSet`
