### ISSUE TITLE
Poptop issues

### ISSUE THREAD

**Issue by zlainsama** [sayterdarkwynd/FrackinUniverse#2794]
1. Certain type of rare poptop causing game music switched to the one that played in space outlaw mine, and messes scripted musics in certain missions. (A [1 minute youtube video](https://youtu.be/IrfKuC8LS5I) about this)
2. Some poptops in Dark Cavern mission can grow up give enough time. (After some afk while my character sleeping in the wooden cart, I noticed several Adult Poptops stuck in walls where only normal poptops can fit in there)
3. Poptop capture quests given by tenants after completion can make those tenants die when captured poptop grow up.

Note: The first one I thought was some other mod or general rare monsters causing it but after some time, I only encounter this music issue when on lush planet and in Dark Cavern mission where both have poptop spawning.

**Comment by sayterdarkwynd** [comment]
none of this is an issue. The music is because different poptops have different music, which can layer.
poptops can evolve into larger poptops. that is also not an issue. Be careful with vicious pets around tenants.

**Comment by zlainsama** [comment]
@sayterdarkwynd 
This music issue was caused in "/scripts/companions/capturable.lua"
There is a fix patch in Steam Workshop called [Pandora's Box - Fixes](https://steamcommunity.com/sharedfiles/filedetails/?id=2107168260), which removed the playing of "/music/desert-battle-2.ogg"
Related modification was the removal of these [3 lines](https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/scripts/companions/capturable.lua#L89-L91).
