### ISSUE TITLE
cthulhureward is (almost) unobtainable

### ISSUE THREAD

**Issue by AlienAtSystem** [sayterdarkwynd/FrackinUniverse#2802]
The item Elder Artefact (cthulureward) is used in about half of the recipes of the Elder Altar equipment, but does not drop from any monster or mission. It appears to have done so, but the corresponding cuthulurewardtreasure object is now unreferenced by any mission or monster.

This leaves the Elder Artefact only obtainable by the loot box table, in which it appears as exceedingly rare reward in the already rare category of LootBoxHigh. I've run the math, and arrived at a chance of almost 1 in 4000 of having this specific item drop.

This basically renders all equipment requiring this item unobtainable as well.

**Comment by sayterdarkwynd** [comment]
That is not an issue. This is by design. You need to locate the source of these super-rares yourself through exploration.

**Comment by AlienAtSystem** [comment]
This is not a satisfactory answer to me. If there is such a source, then state it. Because I searched the code and found that the treasure is _not_ associated with any way to obtain it, except the loot boxes.

**Comment by edwardspec** [comment]
This item has 100% chance to be inside a very visible chest in the elder-themed mission.
As such, it is not unobtainable.
