### ISSUE TITLE
Mechparts oddity

### ISSUE THREAD

**Issue by rwrangler** [sayterdarkwynd/FrackinUniverse#2806]
Hello!
*/vehicles/modularmech/mechparts_body.config.patch

I think I have found oddities in lines 5634 and 5635:
{"op": "add","path": "/vieraproto/stats/healthBonus","value": 1.3},
{"op": "add","path": "/vieraproto/stats/energyBonus","value": 0.7},

**Comment by sayterdarkwynd** [comment]
No, you havent.
