### ISSUE TITLE
Weather Control Device?

### ISSUE THREAD

**Issue by corymcdonough** [sayterdarkwynd/FrackinUniverse#281]
Not sure if this is where you'd prefer I make suggestions but here goes...

Is it possible to code an upgraded version of the Atmospheric Regulator that protects against weather and block-based interactions with poison/acid/iron/etc.? To make it possible to colonize otherwise inhospitable planet/locations due to weather/meteors/etc. Would be nice to have an upgraded version that lets you either determine the weather, guard against certain types of weather, or just prevent it from damaging your base.

I originally thought this is what the Atmospheric Regulator did until I saw the code.

**Comment by corymcdonough** [comment]
Perhaps there's a way to "protect" the blocks from non-PC interactions similar to how Hylotl underwater bases are protected by the shield.

**Comment by sayterdarkwynd** [comment]
These are Issues, not Suggestions.

**Comment by sayterdarkwynd** [comment]
Steam thread is a better place for suggestions, or a PM here or on CF forums.

that said, we cant control the weather at present. Possble that this might change in 1.2, since we are seeing weather changes going on there. We'll see.
