### ISSUE TITLE
Frames' 'queenLifespanBonus' not used.

### ISSUE THREAD

**Issue by fluxxdog** [sayterdarkwynd/FrackinUniverse#2902]
https://github.com/sayterdarkwynd/FrackinUniverse/blob/7195402484671e5017bbf7c06c182fb534c6ee11/bees/apiary.lua#L699

Been reading the code and it seems that the frameBonuses.queenLifeSpan is not used in any calculations, meaning that frames that have such a bonus never actually use it. Would have expected to find something in the ageQueen function at the least.

**Comment by sayterdarkwynd** [comment]
its right in the ageQueen function actually.

	local fullLifespan = genelib.statFromGenomeToValue(queen.parameters.genome, "queenLifespan") * 2.0

**Comment by fluxxdog** [comment]
@sayterdarkwynd  Recieved an e-mail saying this was closed with the comment "its right in the ageQueen function actually" but review of the code does not show the _frameBonus_ used at all. Not the bee's value, the frame bonus value.
