### ISSUE TITLE
No Contaminated Water recipe

### ISSUE THREAD

**Issue by fluxxdog** [sayterdarkwynd/FrackinUniverse#2906]
When unlocking the Liquid Creation node on the Chemistry research tree (liquidcraftinq), one of the unlocked recipes listed is Contaminated Water (liquidwastewater). However, no recipe could be found in game, not even after upgrade the Alchemy table. The miraheze wiki had no recipe listed either. A search of the code base shows no liquidwastewater.recipe.

**Comment by sayterdarkwynd** [comment]
yea, thanks
