### ISSUE TITLE
Power Distribution

### ISSUE THREAD

**Issue by thaelina** [sayterdarkwynd/FrackinUniverse#292]
So I have a small network for power distribution. 6 solar towers feed into a single wire relay. It outputs to a large power sensor, telling me the expected 72. Then it goes out to 3 relays (for neatness sake) each of which is receiving the expected 24v.  Then I output from one wire relay to 2 atmospheric condensers (10v),  1 powder sifter (2v) and 1 arc smelter (12v) for a total of 24v. Yet the arc smelter wont turn on unless I disconnect both atmospheric condensers or one condenser and the sifter.

ScreenCap: http://devcoftb.net/x/21N6.png

**Comment by NotMrFlibble** [comment]
Power splitting is… somewhat simple at the moment; there is a lot of complexity around getting the correct amount of power for each station.  The current compromise is that power output is split equally and power input is requested equally., with the result that ‘unbalanced’ setups such as yours will not work. Drainiage will occur according to what's requested _except where a request exceeds the allocation_ (in which case none is supplied to that device).

You can power the condensers and the smelter from one 24-unit supply: attach the smelter directly and the condensers indirectly. I recommend a separate 4u-supply battery for the sifter.

**Comment by thaelina** [comment]
Alright thanks for the explanation. I'll keep that in mind when redoing the
network.
