### ISSUE TITLE
Submitted for Approval: Seed rarity update

### ISSUE THREAD

**Issue by fluxxdog** [sayterdarkwynd/FrackinUniverse#2943]
While going through and making seeds, I noticed some items that were off. For example, the Genesiberry, despite requiring a T6 research and madness and producing Legendary produce, was considered a Common seed. Some Uncommon seeds required Rare seeds in order to make. Others required some exotic ingredients for otherwise ordinary seeds. To that end, I did an inventory of the currently available seeds and their rarities. I then looked at several criteria for what would be a sensible rarity for them and came up with a spread sheet [here](https://drive.google.com/file/d/1V0ujTMt9u6EwjsgJExxKAz6MU20V9rd5/view?usp=sharing).

My submission is 3 fold. Step one, get approval for this, which you're reading. The linked spreadsheet shows what each seed is currently rated at as well as factors to consider for updating. My conclusions were based on the following:
1. If the seed's Tier was 6 or higher, make it Legendary. Otherwise if Tier 5, Rare. Otherwise if Tier 4, Uncommon. Otherwise, Common.
2. If the seed required a rarer seed in order to create it, raise its rarity to match it.
3. If the seed required an ingredient rarer than it, raise its rarity to one level below the rare ingredient, such as Fungal Ichor (Rare) would cause a Common seed to be Uncommon.
The spreadsheet is open for commenting and, pending approval, will be the basis for the work that I'd take on.

Step two is, of course, to make the rarity changes. This would be submitted in its own PR. Only rarity changes would be made.

Step three is to alter the main produce for the seeds to match. This way, Rare seeds would produce Rare fruit. Other byproducts, such as Plant Fiber, would be left alone. Only rarity changes would be made.

**Comment by sayterdarkwynd** [comment]
glanced over it....i see no issue with the proposed changes. Nothing is moved in progression, and this merely improves consistency. Give it a whirl!

**Comment by fluxxdog** [comment]
That should do it. I slapped myself a little when I realized the seed update and produce update should not be based on one another and adjusted my commits so they could be independent. Also found some other issues and separated them out as their own PR since they were out of scope. Hope this helps!
