### ISSUE TITLE
Capture bot misses certain monsters

### ISSUE THREAD

**Issue by UltraHex** [sayterdarkwynd/FrackinUniverse#2958]
I spent hours crafting and researching and finally got a capture bot, but was disappointed when the first monster we encountered was successfully stunned, but it kept throwing capture balls and none of them worked. I though I'd done something wrong, but then we found a different monster and it worked. I eventually realized that this was consistent depending on the monster and it was just barely missing certain monsters.

I tried setting "fireOffset" to [0, 0] with a patch and it seemed to fix it. I would make a PR but I'm honestly not sure what all this code does and just took a shot in the dark.

https://github.com/sayterdarkwynd/FrackinUniverse/blob/465c7561844391596c37c4ce5b3e58b7492f0e2d/monsters/flyers/servitors/capturebot/servitorcapturebot.monstertype#L66

**Comment by sayterdarkwynd** [comment]
not every monster is capturable. Some have significantly different capture rates and requirements too. if its capturable, and you are within the requirements, it will capture.

**Comment by UltraHex** [comment]
Let me be more clear. There were a couple monsters on my starter planet that were capturable with regular capture balls but the capture bot just kept throwing capture balls at them and missing. When I made the change I described previously it would capture first try every time. This is definitely a bug unless the capture bot is supposed to have perfect bad aim.
