### ISSUE TITLE
Fixed, don't bother reading this.

### ISSUE THREAD

**Issue by IonToIons** [sayterdarkwynd/FrackinUniverse#2966]

**Comment by IonToIons** [comment]
turns out i only had to finish another mission for it to stop crashing

**Comment by Zarra-0** [comment]
1. You're not on SB 1.4.4, and you need to be
2. Your FU instance either failed to download properly, or is badly outdated
3. You have a number of incompatible mods, see this list (https://frackinuniverse.miraheze.org/wiki/Incompatible)
4. Replace 'Improved Containers' with Enhanced Storage (with the patch), it's badly outdated.

**Comment by sayterdarkwynd** [comment]
woudlnt bother reading it anyhow, as this isnt an FU issue, but a user issue.
