### ISSUE TITLE
Cooling/Heating EPP III not working on hot/cold works generated on vanilla

### ISSUE THREAD

**Issue by NinCollin** [sayterdarkwynd/FrackinUniverse#2988]
I was going through my teleporter bookmarks, and I noticed that my Cooling III EPP was not working on a hot planet I had previously visited on vanilla. Further testing reveals that this is also an issue with cold planets visited on vanilla (this could possibly apply to planets with radiation too, but I have not tested it.)

The EPP's definitely work on newly generated planets.

Here are screenshots of me standing on a Midnight planet generated on vanilla and on a Midnight planet generated with Frackin' Universe. 
![Screenshot from 2021-03-26 12-26-09](https://user-images.githubusercontent.com/36493269/112702940-29da2200-8e63-11eb-8148-1445a33b489d.png)
![Screenshot from 2021-03-26 12-38-49](https://user-images.githubusercontent.com/36493269/112702943-2a72b880-8e63-11eb-8f7e-03b44683152c.png)
Notice how the icon for the cold debuff on the vanilla world looks different; the vanilla debuff is "Deadly Chill" while the Frackin' Universe debuff is "Extreme Cold."  

I can post logs or other information if needed.

**Comment by sayterdarkwynd** [comment]
none needed. This is absolutely unavoidable, and one of the reasons we specifically note that you should create a new universe when installing FU. Worlds in FU use different weather statuses than vanilla, and our EPPs are aligned for use on them.

**Comment by NinCollin** [comment]
Couldn't you simply add biomecoldImmunity, biomeheatImmunity, and biomeradiationImmunity to the respective tier III Frackin' Universe EPPs? It's a hacky fix, but would allow backwards compatibility with vanilla-generated worlds. It also wouldn't allow any sequence jumps (since certain vanilla planets can require tier II or III protection when generated with Frackin' Universe.)

I just added biomecoldImmunity to my Cooling EPP III and it works perfectly.
