### ISSUE TITLE
Exclude .git Folder from downloading with GitGUI and GitBash

### ISSUE THREAD

**Issue by Hyperfire** [sayterdarkwynd/FrackinUniverse#3008]
Can you please exclude the "hidden" .git folder from the repository when someone downloads it with Git GUI, Git Bash(git pull) or as .zip?
The folder is 929mb and is unnecessary (And not included in your latest release with the .pak file).

**Comment by sayterdarkwynd** [comment]
yea, good idea. Sick of that folder being a pain in the butt. Will look into this.
