### ISSUE TITLE
Algae-as-farmable is really quite rare?

### ISSUE THREAD

**Issue by renbear67** [sayterdarkwynd/FrackinUniverse#304]
And it really quite shouldn't be? Maybe add more `wildalgaeseed` spawns on Bog worlds, and possibly Fungal worlds as well?

**Comment by Tamamo89** [comment]
Is it really?
I know it's a pain in the ass to spot though.
We could make it bigger actually.

**Comment by sayterdarkwynd** [comment]
id honestly say we can *probably* remove it totally and barely notice. The bog rain and fungal rain + the ore does an ample job of providing a shitload of algae to the user. But that's a matter of preference, since farming it has upsides too.

**Comment by sayterdarkwynd** [comment]
so, we can certainly increase incidence on Bogs and Fungals

**Comment by sayterdarkwynd** [comment]
and done.
