### ISSUE TITLE
monsters that need respriting/replacement sprites

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#306]
Putting this here for my own records.

- [ ] Caterpillar - ????

- [ ] Deep Ones  - lets get that arm attack not looking like he is fisting a goat. Could use swim anims too, etc.

- [x] Doom Spirit  - trace/recolor to get the jaggies out. Nothing too fancy here. The sprite itself LOOKS okay, just really fuckin low-quality (whoever did this likely shrunk the original sprite without using Nearest Neighbor)

- [ ] Giant Bat - Replace with fallen angel from xxxHolic.

- [ ] Flesh Reaper  - ????

- [x] Starspawn  - if you dont mind, I (sayter) would like to handle this one. I have a very specific set of things I want it to do.

- [ ] Shoggoth Worms  - look like dogshit. Should look like small shoggoths. Anims should be weird, 
amorphous things. Feel free to give them numerous different anims if desired rather than one (bite bite bite bite bite)

- [ ] Tideworm - ????

other ideas:
https://s-media-cache-ak0.pinimg.com/564x/47/fc/63/47fc631f34b38ebb8cec82df10e57f87.jpg
https://s-media-cache-ak0.pinimg.com/564x/fc/88/d6/fc88d60acd41f6fc8aa01d5d93420199.jpg

**Comment by Tamamo89** [comment]
@sayterdarkwynd 
Sounds good,
But yeah, you can handle the starspawns.

**Comment by renbear67** [comment]
Added fancy-shmancy checklist for you :-)

**Comment by Tamamo89** [comment]
Thanks a ton, that makes it much easier.
