### ISSUE TITLE
Armour not listed in Upgrades (Geist)

### ISSUE THREAD

**Issue by ulrellik** [sayterdarkwynd/FrackinUniverse#3124]
Hi,
First thank you very much for all the hard work you put into this mod! It's really great.

I encountered a problem with my Avikan character: The Geist armour (https://github.com/sayterdarkwynd/FrackinUniverse/blob/f9ddc3bf9674287b8941dbbe44e7bf3e8e9487da/items/armors/tier6/geist/test1.head) doesn't appear in the list of upgrades opened with the tricorder, although it seems it should (https://frackinuniverse.miraheze.org/wiki/Geist_Helm). Other items appear, e.g. Leviathan armour, shields etc. I don't know if it's a bug or if the description about upgradeable is wrong.

As a side-note, I'm not sure why EEPs like https://github.com/sayterdarkwynd/FrackinUniverse/blob/f9ddc3bf9674287b8941dbbe44e7bf3e8e9487da/items/armors/backitems/protocytepack/batterypack_protocyte.back are listed as Upgradeable EPP, when they also don't appear in the list. Should they or is it related to the other problem above?

Log attached: [starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/6797500/starbound.log) Mods should be all at recent version.

Let me know if I should test anything else.

**Comment by Zarra-0** [comment]
The tricorder interface can only upgrade weapons and armour to tier 6, past that the precursor crucible is required. Geist armour is T6 when crafted.

EPPs are 'upgraded' via crafting the next tier up, not via the tricorder; the Protocite Energy Pack can be crafted into the Antimatter Energy Pack at the Armory.

**Comment by ulrellik** [comment]
@Zarra-0 Ahhh OK thank you very much for the fast reply. I missed this information on the Wiki. For future reference: https://frackinuniverse.miraheze.org/wiki/Personal_Tricorder _"Tool to upgrade all weapons/armors (for Upgrade Modules, up to tier 6) "_

Regarding the EPP, got it! But I find this confusing, the vanilla EPPs are upgraded the same way, but they don't have Category 'Upgradeable EPP' and interesting enough, nor does https://frackinuniverse.miraheze.org/wiki/Antimatter_Energy_Pack, only 'Protocite Energy Pack' and 'Erithian Energy Pack' (which I feel should have the same category as all the other EPPs too). Just my opinion :-)

Keep up the good work!
