### ISSUE TITLE
Tidewater planets kicking me back to the ship

### ISSUE THREAD

**Issue by thaelina** [sayterdarkwynd/FrackinUniverse#316]
I think this was lost when I posted it on the forums so I'm going to post it here.

"Alright, it happened on the first tidewater planet I found.
I warped down then moved a little to the right, maybe 5 steps and bam, warped back to my ship when the world crashed
http://pastebin.com/Y880Vu5W
Looks like its trying to generate a structure."

**Comment by sayterdarkwynd** [comment]
ive attempted this many times , but have yet to replicate the results

**Comment by Beanary** [comment]
Never seen this happen, however once I dived deep into a large tidal world and the ocean began draining at some point. Eventually I reached the bottom and there was little water and was slowl filling, had to go back up placing blocks. After I reached certain height water started falling on top of me, and a bit higher I could swim my way back to the surface. It seems at certain point the background was draining the ocean.

**Comment by renbear67** [comment]
I have reproduced the error. We are investigating.

**Comment by renbear67** [comment]
I have experienced this on a planet I had not been to before now. It may not have been far enough away, but we may need to reopen this.

**Comment by renbear67** [comment]
Confirmed a long, long distance away. Unless I was incredibly unlucky, this is a brand new sector.

**Comment by sayterdarkwynd** [comment]
i think ive fixed it. the cause was likely:



      {
        "mode" : "floor",
        "priority" : 0.0,
        "variants" : 1,
        "distribution" : "/biomes/distributions.config:surfaceCrops",

        "type" : "object",
        "objectSets" : [
          {
            "pool" : [ 
 
            ],
            "parameters" : {
              "startingStage" : 3
            }
          }
        ]
      }



dafuq? apparently I had an empty pool in there.
