### ISSUE TITLE
Research Bonuses not working

### ISSUE THREAD

**Issue by redmoogle** [sayterdarkwynd/FrackinUniverse#3161]
I appear to be stuck at the passive +1 research per second. I've tried wearing the research armor and having a research lad but it appears to tick at the same rate... 

Addendum: Applies to the idiot crown too. Maybe the armor bonuses dont work at all?

I'm using Saturnian race but I dont think anything else should be affecting it.
Also running PopOS but that shouldnt matter

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/6964709/starbound.log)

**Comment by sayterdarkwynd** [comment]
not seeing the issue on our end. seems to be working fine.

**Comment by redmoogle** [comment]
Doesn't change the fact I can't see any observable difference when putting on research bonus items

**Comment by redmoogle** [comment]
https://user-images.githubusercontent.com/20369082/129430034-83d5222f-b9d3-4365-852a-88dc845f7f6e.mp4
