### ISSUE TITLE
Exception caught in client main-loop (ItemException) No such item 'riceseed'

### ISSUE THREAD

**Issue by overtube** [sayterdarkwynd/FrackinUniverse#3166]
[Info] Root: Loaded PlantDatabase in 0.204362 seconds
[Error] Exception caught loading asset: /objects/farmables/rice/riceseed.object, (AssetException) Could not read JSON asset /objects/farmables/rice/riceseed.object
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x72) [0xa92122]
./starbound(_ZN4Star14AssetExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x55) [0xab4eb5]
./starbound(_ZNK4Star6Assets8loadJsonERKNS_9AssetPathE+0x3fa) [0xab445a]
./starbound(_ZNK4Star6Assets9loadAssetERKNS0_7AssetIdE+0x1c5) [0xab2d25]
./starbound(_ZNK4Star6Assets6doLoadERKNS0_7AssetIdE+0x1a) [0xab31da]
./starbound(_ZN4Star6Assets10workerMainEv+0x12f) [0xab3dcf]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star18ThreadFunctionImpl12wrapFunctionESt8functionIS0_EEUlvE_E9_M_invokeERKSt9_Any_data+0x15) [0xa9b685]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/libpthread.so.0(+0x9259) [0x7f543fdde259]
/usr/lib/libc.so.6(clone+0x43) [0x7f543fbaf5e3]
Caused by: (JsonParsingException) Cannot parse json file: /objects/farmables/rice/riceseed.object
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x72) [0xa92122]
./starbound(_ZNK4Star6Assets8readJsonERKNS_6StringE+0x4f8) [0xaaf268]
./starbound(_ZNK4Star6Assets8loadJsonERKNS_9AssetPathE+0x231) [0xab4291]
./starbound(_ZNK4Star6Assets9loadAssetERKNS0_7AssetIdE+0x1c5) [0xab2d25]
./starbound(_ZNK4Star6Assets6doLoadERKNS0_7AssetIdE+0x1a) [0xab31da]
./starbound(_ZN4Star6Assets10workerMainEv+0x12f) [0xab3dcf]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star18ThreadFunctionImpl12wrapFunctionESt8functionIS0_EEUlvE_E9_M_invokeERKSt9_Any_data+0x15) [0xa9b685]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/libpthread.so.0(+0x9259) [0x7f543fdde259]
/usr/lib/libc.so.6(clone+0x43) [0x7f543fbaf5e3]
Caused by: (JsonParsingException) Error parsing json: unexpected character parsing word at 32:33
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star20JsonParsingExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x52) [0xa00b12]
./starbound(_ZN4Star13inputUtf8JsonIPcEENS_4JsonET_S3_b+0x66a) [0xac19ea]
./starbound(_ZNK4Star6Assets8readJsonERKNS_6StringE+0xe6) [0xaaee56]
./starbound(_ZNK4Star6Assets8loadJsonERKNS_9AssetPathE+0x231) [0xab4291]
./starbound(_ZNK4Star6Assets9loadAssetERKNS0_7AssetIdE+0x1c5) [0xab2d25]
./starbound(_ZNK4Star6Assets6doLoadERKNS0_7AssetIdE+0x1a) [0xab31da]
./starbound(_ZN4Star6Assets10workerMainEv+0x12f) [0xab3dcf]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star18ThreadFunctionImpl12wrapFunctionESt8functionIS0_EEUlvE_E9_M_invokeERKSt9_Any_data+0x15) [0xa9b685]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/libpthread.so.0(+0x9259) [0x7f543fdde259]
/usr/lib/libc.so.6(clone+0x43) [0x7f543fbaf5e3]
[Error] Error loading object file /objects/farmables/rice/riceseed.object: (AssetException) Error loading asset /objects/farmables/rice/riceseed.object
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star14AssetExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x52) [0xab4e22]
./starbound(_ZN4Star14AssetException6formatIJNS_9AssetPathEEEES0_PKcDpRKT_+0x1b) [0xab5cbb]
./starbound(_ZNK4Star6Assets8getAssetERKNS0_7AssetIdE+0x10c) [0xab341c]
./starbound(_ZNK4Star6Assets4jsonERKNS_6StringE+0x63) [0xab34d3]
./starbound(_ZN4Star14ObjectDatabaseC1Ev+0x175) [0xdecde5]
./starbound(_ZNSt17_Function_handlerIFSt10shared_ptrIN4Star14ObjectDatabaseEEvEZNS1_4Root10loadMemberIS2_JEEES0_IT_ERS8_RNS1_5MutexEPKcDpOT0_EUlvE_E9_M_invokeERKSt9_Any_data+0x43) [0xf47ad3]
./starbound(_ZN4Star4Root14objectDatabaseEv+0xd1) [0xf3c941]
./starbound(_ZNSt17_Function_handlerIFvvEN4Star13SwallowReturnISt5_BindIFSt7_Mem_fnIMNS1_4RootEFSt10shared_ptrIKNS1_14ObjectDatabaseEEvEEPS5_EEEEE9_M_invokeERKSt9_Any_data+0x24) [0xf4b294]
./starbound() [0xa8dff9]
./starbound(_ZN4Star10WorkerPool12WorkerThread3runEv+0x5f) [0xa8eddf]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/libpthread.so.0(+0x9259) [0x7f543fdde259]
/usr/lib/libc.so.6(clone+0x43) [0x7f543fbaf5e3]

**Comment by sayterdarkwynd** [comment]
has absolutely nothing to do with FU.
