### ISSUE TITLE
 Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/objects/colonysystem2/colonydeedmk2/colonyde..."]:23: attempt to index a nil value (field 'occupier')

### ISSUE THREAD

**Issue by dan-xin** [sayterdarkwynd/FrackinUniverse#3175]
An error report about multiple people using mod to start the server with high frequency

**Comment by dan-xin** [comment]
![图片](https://user-images.githubusercontent.com/49889051/133479312-2835f103-8bfc-4203-a85e-f9319fe5d741.png)

**Comment by sayterdarkwynd** [comment]
This has nothing to do with frequency and everything to do with the colony system.
