### ISSUE TITLE
Teleported into a world and appeared deep inside instead of in the surface.

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#320]
This is with version 4.17.0 of the mod. Only other mods I am using are frackin music and novaskin ( novakid skin replacer ) which shouldn't cause conflict I believe.

I Am posting the coordinates of the system in case you can check it out.

 x 262735238 y -642647893

The planet is the green one shown in the screenshot. Since it's a high difficulty planet I do not know if this behaviour is intentionate or a bug. Thank you in advance.

http://images.akamai.steamusercontent.com/ugc/266100190170543412/2495F9925F31DCBABF0DA7E2D058FEDBEE1550DF/

**Comment by sayterdarkwynd** [comment]
its an unknown world. They are literally 100% random. That means sometimes the biomes clash and funny things happen. Part of the risk.
