### ISSUE TITLE
Agaran Sellsword AssetException when using its weapon (poisonballoon)

### ISSUE THREAD

**Issue by ulrellik** [sayterdarkwynd/FrackinUniverse#3210]
Hi,

When the Agaran Sellsword gives me company on a planet as crew member and fights of enemies, I observed this error popping up in the logs:

`[19:29:22.696] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:2', using placeholder default.
(AssetException) No such frame 2 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames
[19:29:22.773] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:3', using placeholder default.
(AssetException) No such frame 3 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames
[19:29:22.834] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:23', using placeholder default.
(AssetException) No such frame 23 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames`

There's nothing really visually going wrong, at least not smth I can see, so this is probably low prio.

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/7438087/starbound.log)

**Comment by sayterdarkwynd** [comment]
Looks like this might be a conflict on your side or something.

poisonballoon projectile file is configured to have 2 frames, and its frames file also contains that many. I am unclear where it is getting 3 or 23 from.

**Comment by Kherae** [comment]
/projectiles/mushroom/shroomcloud/shroomburstshot.projectile@7

**Comment by ulrellik** [comment]
@Kherae I'm not sure if I can follow you, does this mean it should be :2 indicating 2 frames instead of :24, so only a little typo?

Anyways I followed @sayterdarkwynd hint and tried it with a complete different universe/player that had much lesser mods, and the problem stayed, now with other frame numbers:

> [18:55:07.038] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:2', using placeholder default.
> (AssetException) No such frame 2 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames
> [18:55:07.123] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:3', using placeholder default.
> (AssetException) No such frame 3 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames
> [18:55:07.191] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:23', using placeholder default.
> (AssetException) No such frame 23 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames
> [18:55:10.522] [Error] Could not load image asset '/projectiles/mushroom/shroomcloud/poisonballoon.png:4', using placeholder default.
> (AssetException) No such frame 4 in frames spec /projectiles/mushroom/shroomcloud/poisonballoon.frames

[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/7447960/starbound.log)

**Comment by Kherae** [comment]
what it means is that the projectile is referencing nonexistent frames. the incorrect value is the 24, which should be 2.

**Comment by ulrellik** [comment]
@Kherae Thumbs up for you! This seemed to fix the error on my side.
@sayterdarkwynd PR is open for this.
