### ISSUE TITLE
Minor: no music in slime underground sub biome

### ISSUE THREAD

**Issue by RusTit** [sayterdarkwynd/FrackinUniverse#3262]
So, the topic.
I almost sure that this is not big issue, but due traveling I got that there was no music there at all.
I also was going up through it and pass spider/web sub biome and there was also no music there. The music started, when I was near the surface.

Slime underground sub biome:
![006](https://user-images.githubusercontent.com/29846693/147867241-5de27a0d-b2c3-4362-a1ec-9eeb09284aac.png)
![007](https://user-images.githubusercontent.com/29846693/147867242-665c1abe-f5d1-4ece-bcc4-fdf47d8bcafb.png)
![008](https://user-images.githubusercontent.com/29846693/147867244-5b82d37a-e521-44cd-9395-f3674fd0eecd.png)

Logs:
https://pastebin.com/aMENdHUh

**Comment by edwardspec** [comment]
This is vanilla biome: https://starbounder.org/Luminous_Caves

**Comment by RusTit** [comment]
So, it means that this is original bug/feature. Ok, no issues then.
