### ISSUE TITLE
Meremen (large fish people from elder biome) bug

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#329]
As of 4.18.0 the Meremen are no longer working properly, they use their ranged attack and initiate walking animations but never get to move from their position. They used to work fine up to 4.17.0

**Comment by renbear67** [comment]
Wait, they were working before, and now they aren't?!? Calling @sayterdarkwynd

**Comment by sayterdarkwynd** [comment]
no, they have been broken since 1.1 or 1.1.1. Known issue. in waiting for the new sprites.
