### ISSUE TITLE
Feature: Starship battles

### ISSUE THREAD

**Issue by Diniden** [sayterdarkwynd/FrackinUniverse#3306]
This is a feature I'd love to see and would be willing to help on it (after I learn starbound's mod system some). This may be a pie in the sky feature to make happen, but it seemed like a ridiculously fun thing to attempt creating and see someday.

Starship battles:

- Possibly random engagements as you fly around, or make them normal encounters like other typical events
- Your ship appears on the left, adversary on the right, asteroid field between
- Mounted turrets and weapons on your ships fire at each other (enemy deploys minions), firepower slowly eats the asteroid field up. Large torpedos etc pose grave threat to each others ships and your mech.
- You deploy your mech to engage enemy with goal of disabling enemy ship while battle ensues (use asteroid field to avoid massive firepower...upgrade mech to be more "starship battle" capable etc)
- Victory condition: eliminate all weapons systems of each others ships OR destroy / disable the core of the ship (required core to make battles possible or make the FTL drive the core). Mechs can burrow through ship materials (probably decreased rate)
- Loss condition: lose your core or lose all of your weapons
- Win: gain resources from "salvaging" the battlefield, take no damage (possibly light damage? but doesn't sound fun having to do partial repairs, mebbe just use some fuel?).
- Lose: Place weapons into "disrepair" where you need to repair them and expend resources. Can't fight again till all weapons back online. (keep the FTL so you aren't stuck in a system somewhere)

My overall thought on this is just to experience firepower mayhem something bullet-hell like (but not patterned...more random). Would give a LOT of cred to the BYOS system and make space a lot more engaging.

I don't see a README or docs here for information how to discuss these things with you (I really only use your github to get latest mod updates), so I thought I'd give it a shot by posting here.

**Comment by Zarra-0** [comment]
There's a discord linked on the mod page and on the Miraheze wiki's main page.

The properties of the shipworld aren't amenable to these sorts of changes, so it would most likely need to take place on a separate instance - which would preclude bringing the player's BYOS ship (or a copy of it) to the instance. I'd guess that a viable form of this amounts to essentially being a much more complex version of a pirate ship space encounter crossed with a mission, requiring a lot of new objects, enemies and scripting work. In that form it's likely possible, though it's a lot of work for not that much gain. If you manage to come up with something fun feel free to PR it and we'll take a look.

**Comment by Diniden** [comment]
would be happy to investigate :)

Thanks for pointing me toward the discord. I'll try to get involved via that route and see where that takes me.

Thanks for the initial direction of looking at it from an instancing perspective. Shall see where that goes. First thing first will be to figure out the dev-ops you all have going.
