### ISSUE TITLE
Master Manipulator Issue

### ISSUE THREAD

**Issue by snowboundmage2** [sayterdarkwynd/FrackinUniverse#3350]
My Master manipulator only starts of with 2x2 tiles, is this right? The wiki says 10x10. The morphite manipulator had it's stats as advertised. 
The tile breaking speed does seem to be as fast if not faster than my t11 mining laser, and had both the wiring and paint unlocked by default as well.
And is it still the best manipulator? the morphite and quantum manipulator both seem way harder to get.

**Comment by sayterdarkwynd** [comment]
You likely have conflicts installed. That manipulator hasnt been adjusted in years and there is zero reason it would suddenly break.

Yes, the master is still the best: you cannot obtain it, period, until you have completed the entire game.

This is a space for verified bug reports, not Q&A: Please direct these things to discord in the future.
