### ISSUE TITLE
Release version and mod version always mismatching

### ISSUE THREAD

**Issue by Zeiver** [sayterdarkwynd/FrackinUniverse#3395]
Just wondering why the versions are mismatching.
And what versioning is this project using?
It would be weird if it is using semantic versioning since the patch version is getting increased weirdly.

**Comment by Zeiver** [comment]
Now I saw that the workshop version is using the correct version, but the version of the pak files in the releases are wrong.
Is it possible to fix it, so that the people who don't want to use the workshop can use the github pak file?

**Comment by sayterdarkwynd** [comment]
It's so minor that I literally do not care about it.

This is generally due to how steam and github update differently, leading to one or the other saying a slightly wrong number.
