### ISSUE TITLE
Crimson Brave Armor tooltip

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#340]
It says in the tooltip that it gives pus inmunity, I am still getting toxic puss debuff when I step on it on full Crimson Brave armor. This was with 4.18.1 have to confirm the issue.

**Comment by Beanary** [comment]
Still the same issue, different planet far away and 4.18.2 It's either a bug or a tooltip error. If you need logs or something let me know.

**Comment by sayterdarkwynd** [comment]
thanks. forgot a blocking stat in the pus effect. will be corrected next release.
