### ISSUE TITLE
Cultist staff tooltip error

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#341]
I have 2 cultist staff recipes, the first (weaker) one if properly named, second has an error in the tooltip

[Bugged tooltip image](http://images.akamai.steamusercontent.com/ugc/266100190183269918/DAD6256DCF1D69DBD34847B294BF95A5D60D3E20/)

**Comment by sayterdarkwynd** [comment]
not sure why that happens. It's as it should be in the file.
