### ISSUE TITLE
Fragments of Ruin race Healing water damaging effect not working

### ISSUE THREAD

**Issue by IronX5000** [sayterdarkwynd/FrackinUniverse#3417]
The effect that hurt Fragments of Ruin instead of healing them when in healing water doesn't work, I still get healed.

I Looked into the effects files to see about it and everything should be working, no idea why but It doesn't.

**Comment by edwardspec** [comment]
Look like it was never implemented (there is nothing of the sort in `species/fragmentedruin.raceeffect`, only in the `.species.patch` file, which is a human-readable description).

**Comment by edwardspec** [comment]
Looks like it was never implemented (there is nothing of the sort in `species/fragmentedruin.raceeffect`, only in the `.species.patch` file, which is a human-readable description).

**Comment by IronX5000** [comment]
It's actually in the regen_healingwater.lua

There is something that should do poison damage to the fragments but it doesn't seem to work.

**Comment by IronX5000** [comment]
And the thing that heals them when poisoned is in the weakpoison.lua

**Comment by sayterdarkwynd** [comment]
This isn't an officially supported race.

**Comment by IronX5000** [comment]
Then who added those modifications? I tried making a patch but it just get ignored by the mod.

**Comment by sayterdarkwynd** [comment]
Because unless you add a "requires" field to data file of the patch mod it will always load before FU does, thus being overwritten.

**Comment by IronX5000** [comment]
Okay just to be sure, can you confirm this inside healingwater.statuseffect.patch
[
  {
    "op": "replace",
    "path": "/scripts/0",
    "value": "regen_healingwater.lua"
  }
]

does what I think, which is replacing the script used in healingwater.statuseffect in the base game (which use regeneration.lua)

If yes, then that means the problem only comes from regen_healingwater.lua

**Comment by IronX5000** [comment]
So I managed to get around the issue -maybe you can't patch a script I don't know- by patching the liquid and replacing the effect with a new one that uses the correct script. Hooray.
