### ISSUE TITLE
Sting needler still 2 handed

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#343]
Now it has a 1 hand animation but it's a 2 handed weapon, or maybe this is just for old weapons and I need to find a new one to be properly 1 handed?

[animation image](http://images.akamai.steamusercontent.com/ugc/266100190184598925/2E7A3E1CCF1C8610B4EC604BD5F5784B92B05D54/)

[tooltip image](http://images.akamai.steamusercontent.com/ugc/266100190184599640/4DCD849D3C74E419F474B27C94D84A3D5992998A/)

**Comment by sayterdarkwynd** [comment]
yes i know. thanks.
