### ISSUE TITLE
Lab pillar block displays incorrect sprite when painted 

### ISSUE THREAD

**Issue by Ramiels** [sayterdarkwynd/FrackinUniverse#3432]
It would appear that the sprite gets offset when painted, getting worse and worse as the color progresses. Not too familiar with how blocks are implemented in Starbound/FU but I assume there's just extra padding between a spritesheet for colors, and it's causing the painted sprites to be offset incorrectly. I've included an image below, where I painted some Lab Pillar blocks from the first color (red) to the last (white) from bottom up, and there's some unpainted lab pillar block at the very top to show the *not* messed up sprite.
![image](https://user-images.githubusercontent.com/54731850/202304242-60dcca8b-a9ad-496c-8d71-6c034dd55dc4.png)

**Comment by sayterdarkwynd** [comment]
it isnt dyeable. Any non-dyeable block does this.
