### ISSUE TITLE
Wired Support block has visual issues when painted

### ISSUE THREAD

**Issue by Ramiels** [sayterdarkwynd/FrackinUniverse#3433]
Included below are some screenshots as of version 6.3.1, it should be easy to reproduce in game but the sprite tends to change between the corner of a block, some transluscent shadow, and entirely vanishing.
![image](https://user-images.githubusercontent.com/54731850/202305524-b45da92d-9433-4b80-9c79-a044b14e1884.png)
![image](https://user-images.githubusercontent.com/54731850/202305955-3cf3c1a7-da73-452f-a2e9-6be303fd6f05.png)

**Comment by sayterdarkwynd** [comment]
not dyeable.
