### ISSUE TITLE
Avali race can't use BYOS properly

### ISSUE THREAD

**Issue by Dark-Matter-X** [sayterdarkwynd/FrackinUniverse#3435]
![204097153-8074b78a-0156-4544-bf78-1e693711523c](https://user-images.githubusercontent.com/72060700/204101251-4baefa24-c535-4bd5-966a-ce02452a2ed0.png)
I already installed that patch before creating character, but this message is showing up.

**Comment by sayterdarkwynd** [comment]
Yes they can. We have Avali on our official server and they do not have this issue. This is not an FU issue. You likely have other incompatible mods installed. 

There is info on the patches to use and incompatible mods on the FU page.
