### ISSUE TITLE
Lower tier of Fission from Adv. Alloy

### ISSUE THREAD

**Issue by anoobindisguise** [sayterdarkwynd/FrackinUniverse#3441]
Adv. Alloy makes fission very difficult to obtain and I find myself usually just skipping over it for Fusion which isn't that much harder to obtain. Lowering the material to Titanium or Durasteel or otherwise adding a "Small Fusion Reactor" equivalent of the fission reactor would make it a more attractive option. I don't know whether Alloys are still slated for removal.

**Comment by sayterdarkwynd** [comment]
Its fine exactly where it is in the tier sequence. I do not view this as an "issue".
