### ISSUE TITLE
Can't eat while wearing helmet

### ISSUE THREAD

**Issue by azah** [sayterdarkwynd/FrackinUniverse#346]
User has to remove helmet in order to eat.

**Comment by Beanary** [comment]
uhh what helmet were you wearing? I haven't experienced such issue and I'm wearing helmet all the time.

**Comment by azah** [comment]
Ah should've specified sorry: X10 helmet.

**Comment by sayterdarkwynd** [comment]
uh... that wouldnt affect eating. Nothing on that helm has anything to do with food.

**Comment by azah** [comment]
Could it be the status effect from the set bonus then? Removing the helm would remove that.

**Comment by Beanary** [comment]
I have tested equiping my X10 armor (with no vanity armor to be sure) and I could eat jsut fine. Perhaps your charater was full when you tried to eat and in the little time it took you to remove helmet debuff wore off? (it looks like a ham with a prohibition sign on top). I sometimes get issues getting to use stuff straigh from my inventory,  but it just takes a few tries and it happens to me in the vanilla game too.

Also were you sitting in the captain chair of your ship while tryign to eat? cause that would prevent it too.

**Comment by azah** [comment]
I still can't. I'm wearing only full X10 armor. (And I just updated to the most recent commit).
The status effects with the suit are: Nova, Run Boost, Xeno, X-Gas. Removing the helm removes X-Gas, and then I can eat.

**Comment by sayterdarkwynd** [comment]
so it is a non-issue then. Closing. I can eat just fine.

**Comment by azah** [comment]
It only appears to be an issue with Gaze Lemon, which is a food item, and should be able to be eaten while wearing the helm.

**Comment by NotMrFlibble** [comment]
It's blocked due to the `headlamp` status effect, which the helmet also applies.
