### ISSUE TITLE
Mystery world issues

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#347]
I know mystery worlds are supposed to be very random but isn't this a bit too strange?

[Permanently draining poison ocean under the ocean](http://images.akamai.steamusercontent.com/ugc/266100190186996799/AC8BFF43BCEA516325D63F04009B2F6DE1627A23/)

[Part of a Hylotl settlement sunken under the sea](http://images.akamai.steamusercontent.com/ugc/266100190186997499/FA41024EDC8344C26189718B88BBD275217656AB/)

Notice the permanently draining ocean at the edges of the roofs, that's what makes it very strange.

**Comment by sayterdarkwynd** [comment]
no. thats the entire point. random.

I'm all for reporting issues. But not any little thing, man.
