### ISSUE TITLE
6.3.61 [Error] Could not apply patch from file REOPEN

### ISSUE THREAD

**Issue by Hyperfire** [sayterdarkwynd/FrackinUniverse#3488]
https://github.com/sayterdarkwynd/FrackinUniverse/issues/3487#issue-1788357806

I've verified my game files, removed all other mods so only FU is installed, this is definitely a problem with FU.
I know you say you didn't touch it in the update, but the error is only in the new update, not in 6.3.5.

Please verify it yourself before you close the issue again.

PS: The error is in the dedi server log.

**Comment by sayterdarkwynd** [comment]
Yea, that's my bad. Github claimed the last change was months ago for the file, but it seems someone did in fact edit it but I was not aware.

**Comment by Kherae** [comment]
fixed in https://github.com/sayterdarkwynd/FrackinUniverse/pull/3489
