### ISSUE TITLE
Game now continues to crash after building an array of trays to farm food items

### ISSUE THREAD

**Issue by HugKitten** [sayterdarkwynd/FrackinUniverse#3496]
Crashes on both proton compatibility mode (linux compatibility layer), and starbound native (Native build for linux). Had hours of play time where things worked fine up into this point.
[List of mods](https://steamcommunity.com/sharedfiles/filedetails/?id=3018317750) 
[Storage folder](https://drive.google.com/file/d/1lLtS51D4OLKGZTr8tCoIdWWXVGkdnKgK/view?usp=sharing) 
[starbound.log](https://pastebin.com/aEcmtSR8) 

### Steps to reproduce
1. Download the mods
2. Add storage files and folders into your starbound storage directory
3. Create a new save, and enter the game, eventually making your choice of BYOS starter ships
3. Observe that the game does not crash and seems to not have any issues
4. Logout of that character and play using the last played Sarah character (The neko race one)
5. Observe the game run fine for about a second before freezing and eventually crashing.

**Comment by HugKitten** [comment]
Added "return; " to the first line after update(dt) in isn_unifiedgrowingtray.lua and it no longer crashes. Seems something is causing the engine to crash here?

**Comment by HugKitten** [comment]
After some debugging, I must have done something to fix the state, because my current save does not have this issue.

**Comment by Kherae** [comment]
insufficient detail, need more info. what was in the trays?  'line after growplant' which one? the function declaration on line 253, or when it's called  on line 87?
I'm not inclined toward downloading all of your mods to test this, nor am I going to download your 400 megabyte storage folder.

**Comment by HugKitten** [comment]
It was a 10x10 array of trays with seeds and the likes in them. I was referring to the function not the call. I seem to be getting the bug again after extending my storage network.

**Comment by Kherae** [comment]
`sb.logInfo("growPlant:fu_sendOrStoreItems 1: %s",{item=item, name1 = item.name, name2 = storage.currentseed.name, seedavoid = seedavoid, inputslots = inputSlots})`
put this preceeding the following in the growplant function
`fu_sendOrStoreItems(0, item, item.name == storage.currentseed.name and seedavoid or inputSlots)`
			
			
do the same at the next sendorstore call with these:
`sb.logInfo("growPlant:fu_sendOrStoreItems 2: %s",{currentseed = storage.currentseed, seedavoid = seedavoid})`
placed above
`fu_sendOrStoreItems(0, storage.currentseed, seedAvoid)`

play with these til you get a crash, provide another log

**Comment by HugKitten** [comment]
It seems it crashes before hitting any of the logs. I uncommented the the other loginfo calls to show that it was still logging properly:
[isn_unifiedgrowingtray.lua](https://pastebin.com/0dybXgQD)
[starbound.log](https://pastebin.com/Y2CTZRqq)

**Comment by HugKitten** [comment]
This may be an issue with the storage network not with trays.

**Comment by Kherae** [comment]
very unlikely it's item network code. if your touching the trays is causing it to not error, that means it's doing something with items that the engine doesnt like. and i'm honestly surprised you havent tried the 'brute force trace' approach...add a log printout before every damn statement in the growplant function (with different text). so...go try that for me.
