### ISSUE TITLE
UPS(Updates Per Second) Lag in settlements on large planets

### ISSUE THREAD

**Issue by Mixarar** [sayterdarkwynd/FrackinUniverse#3499]
So my issue is that on large planets, in generated settlements, the FPS is stable 100+, however the closer i get to the settlement the more and more lag NPCs and items experience, and when i am in the settlements the lag is so much sometimes that the NPCs just teleport every second or two instead of walking.
I wonder if there is a config or smth that can mitigate this, or maybe its another mod being unoptimized, however that would be really hard to find. And the Lag itself is stable(if i can say that), it only happens in settlements on large planets and nowhere else.

Edit: any suggestions on what can i do?

**Comment by sayterdarkwynd** [comment]
This is a starbound issue, not a mod issue.
