### ISSUE TITLE
Question about a monster behaviour

### ISSUE THREAD

**Issue by Beanary** [sayterdarkwynd/FrackinUniverse#352]
This mob that sometimes spawns on planets that attacks everything that is not of its kind, that includes npcs and other monsters. Is that behaviour intentional?

[Angry little creature](http://images.akamai.steamusercontent.com/ugc/266100825022717542/92385B026514F7D1C1BC69B11F518BA45BB8A812/)

**Comment by renbear67** [comment]
Ah, the rat-things. Yes. Quite intentional. I love those things.

**Comment by Beanary** [comment]
Oh! Thank you. Yeah, I love the idea too.
