### ISSUE TITLE
Veluu Doors and Hatches have invisible, wrong, or non-animated sprites.

### ISSUE THREAD

**Issue by kasanryukin** [sayterdarkwynd/FrackinUniverse#3547]
Veluu ship doors and hatches have no animated, closed, (or in the case of the hatch, a correct) sprites.

I can't even capture a screenshot of the issue because the holograph for placement disappears when trying to take a screenshot through both windows and steam, as well as the snippet tool.

Steps to reproduce:
Start a new character as a Vel'uuish
Chose a fracken ship, select Non-rusty (the two floored version)
See that the doors are supposedly open, but actually closed.
Hit E to interact with the doors and hatch. See them open with sound, but the sprite hasn't changed.

**Comment by sayterdarkwynd** [comment]
They seem to work perfectly fine.

**Comment by sayterdarkwynd** [comment]
closing
