### ISSUE TITLE
Colony core with negative happiness gives maximum pixel amount

### ISSUE THREAD

**Issue by GabrielF-C** [sayterdarkwynd/FrackinUniverse#3552]
## Description

Having a Colony Core with negative happiness outputs 16777216 pixels (the max stack size for pixels).
Likely some sort of overflow error.

## Colony setup to reproduce

Colony core : 
- Tenants : 8
- Total Happiness : -3

Colony Addons :
- Recycling Center {+1}
- Sewage Storage {+2}
- Blood Drive {-1}
- Hidden Camera Network {-5}
- Drug Diffuser (powered) {-10}

## Starbound Version

- Starbound 1.4.4 (windows i386)

## FU Mods

- Frackin' Universe
- Frackin' Interface
- Frackin' Music

## Other Mods

- FU/ztarbound S.A.I.L. Modded Race Support
- Feb's Cuter Felins - Furred Version
- [OFFICIAL] FU BYOS Modded Race Patch
- Make the universe a cuter place
- felin towns on frackin' planets
- bk3k's Inventory
- Enhanced Storage
- Improved Food Descriptions
- Felin Costumes+
- Felin Fur+
- Felin Objects+
- Felin
- Felin intro mission

**Comment by sayterdarkwynd** [comment]
Thanks. Nice find!

**Comment by Kherae** [comment]
added fix to https://github.com/sayterdarkwynd/FrackinUniverse/pull/3553
