### ISSUE TITLE
rainbow forest biome issues

### ISSUE THREAD

**Issue by kizeren** [sayterdarkwynd/FrackinUniverse#3585]
Unable to visit certain planets.  Happened to a proto planet, failed to save the log for that.  This one is  planet with a rainbow forest biome.

`[20:21:01.183] [Info] UniverseServer: Creating celestial world 558995760:787755344:-133702543:4
[20:21:01.228] [Error] Exception caught loading asset: /biomes/distributions.config:uncommonRandomMFM, (AssetException) Could not read JSON value /biomes/distributions.config:uncommonRandomMFM
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x72) [0xa92122]
./starbound(_ZN4Star14AssetExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x55) [0xab4eb5]
./starbound(_ZNK4Star6Assets8loadJsonERKNS_9AssetPathE+0x351) [0xab43b1]
./starbound(_ZNK4Star6Assets9loadAssetERKNS0_7AssetIdE+0x1c5) [0xab2d25]
./starbound(_ZNK4Star6Assets6doLoadERKNS0_7AssetIdE+0x1a) [0xab31da]
./starbound(_ZNK4Star6Assets8getAssetERKNS0_7AssetIdE+0x4b) [0xab335b]
./starbound(_ZNK4Star6Assets4jsonERKNS_6StringE+0x63) [0xab34d3]
./starbound(_ZN4Star21BiomeItemDistributionC2ERKNS_4JsonEmf+0x5da) [0xb57a0a]
./starbound(_ZNK4Star13BiomeDatabase19readBiomePlaceablesERKNS_4JsonEmf+0x3b1) [0xb4da01]
./starbound(_ZNK4Star13BiomeDatabase11createBiomeERKNS_6StringEmff+0x5aa) [0xb4e86a]
./starbound(_ZN4Star11WorldLayout11buildRegionEmRKNS0_12RegionParamsE+0x3a6) [0x1165746]
./starbound() [0x1169cd9]
./starbound(_ZN4Star11WorldLayout8addLayerEmiiRKNS_6StringENS0_12RegionParamsES4_NS_4ListIS4_SaIS4_EEES7_NS_6VectorIfLm2EEES9_+0x20b) [0x116a5fb]
./starbound() [0x116ba3a]
./starbound(_ZN4Star11WorldLayout22buildTerrestrialLayoutERKNS_26TerrestrialWorldParametersEm+0x16b) [0x11705eb]
./starbound(_ZN4Star13WorldTemplateC2ERKNS_19CelestialCoordinateERKSt10shared_ptrINS_17CelestialDatabaseEE+0x216) [0x11f1a26]
./starbound() [0x109c274]
./starbound() [0x109c9ac]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star10WorkerPool11addProducerISt10shared_ptrINS1_17WorldServerThreadEEEENS1_17WorkerPoolPromiseIT_EESt8functionIFS8_vEEEUlvE_E9_M_invokeERKSt9_Any_data+0x26) [0x10b7086]
./starbound(_ZN4Star10WorkerPool12WorkerThread3runEv+0x5f) [0xa8eddf]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x89134) [0x7f83f19c9134]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc) [0x7f83f1a497dc]
Caused by: (TraversalException) No such key 'uncommonRandomMFM' in pathGet("uncommonRandomMFM")
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star8JsonPath18TraversalException6formatIJNS_6StringES3_EEES1_PKcDpRKT_+0x9b) [0xa01bab]
./starbound(_ZN4Star8JsonPath7pathGetINS_4JsonEEET_S3_St8functionIFNS0_8TypeHintERNS_6StringERKS6_RNS_15U8ToU32IteratorIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEDiEESM_EES9_+0x212) [0xa02372]
./starbound(_ZNK4Star4Json5queryERKNS_6StringE+0x55) [0x9fd955]
./starbound(_ZNK4Star6Assets8loadJsonERKNS_9AssetPathE+0x161) [0xab41c1]
./starbound(_ZNK4Star6Assets9loadAssetERKNS0_7AssetIdE+0x1c5) [0xab2d25]
./starbound(_ZNK4Star6Assets6doLoadERKNS0_7AssetIdE+0x1a) [0xab31da]
./starbound(_ZNK4Star6Assets8getAssetERKNS0_7AssetIdE+0x4b) [0xab335b]
./starbound(_ZNK4Star6Assets4jsonERKNS_6StringE+0x63) [0xab34d3]
./starbound(_ZN4Star21BiomeItemDistributionC2ERKNS_4JsonEmf+0x5da) [0xb57a0a]
./starbound(_ZNK4Star13BiomeDatabase19readBiomePlaceablesERKNS_4JsonEmf+0x3b1) [0xb4da01]
./starbound(_ZNK4Star13BiomeDatabase11createBiomeERKNS_6StringEmff+0x5aa) [0xb4e86a]
./starbound(_ZN4Star11WorldLayout11buildRegionEmRKNS0_12RegionParamsE+0x3a6) [0x1165746]
./starbound() [0x1169cd9]
./starbound(_ZN4Star11WorldLayout8addLayerEmiiRKNS_6StringENS0_12RegionParamsES4_NS_4ListIS4_SaIS4_EEES7_NS_6VectorIfLm2EEES9_+0x20b) [0x116a5fb]
./starbound() [0x116ba3a]
./starbound(_ZN4Star11WorldLayout22buildTerrestrialLayoutERKNS_26TerrestrialWorldParametersEm+0x16b) [0x11705eb]
./starbound(_ZN4Star13WorldTemplateC2ERKNS_19CelestialCoordinateERKSt10shared_ptrINS_17CelestialDatabaseEE+0x216) [0x11f1a26]
./starbound() [0x109c274]
./starbound() [0x109c9ac]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star10WorkerPool11addProducerISt10shared_ptrINS1_17WorldServerThreadEEEENS1_17WorkerPoolPromiseIT_EESt8functionIFS8_vEEEUlvE_E9_M_invokeERKSt9_Any_data+0x26) [0x10b7086]
./starbound(_ZN4Star10WorkerPool12WorkerThread3runEv+0x5f) [0xa8eddf]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x89134) [0x7f83f19c9134]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc) [0x7f83f1a497dc]
[20:21:01.289] [Error] UniverseServer: error during world create: (BiomeException) Failed to parse biome: 'rainbowforest'
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x72) [0xa92122]
./starbound(_ZN4Star14BiomeExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt9exception+0x55) [0xb4fe05]
./starbound(_ZNK4Star13BiomeDatabase11createBiomeERKNS_6StringEmff+0x1352) [0xb4f612]
./starbound(_ZN4Star11WorldLayout11buildRegionEmRKNS0_12RegionParamsE+0x3a6) [0x1165746]
./starbound() [0x1169cd9]
./starbound(_ZN4Star11WorldLayout8addLayerEmiiRKNS_6StringENS0_12RegionParamsES4_NS_4ListIS4_SaIS4_EEES7_NS_6VectorIfLm2EEES9_+0x20b) [0x116a5fb]
./starbound() [0x116ba3a]
./starbound(_ZN4Star11WorldLayout22buildTerrestrialLayoutERKNS_26TerrestrialWorldParametersEm+0x16b) [0x11705eb]
./starbound(_ZN4Star13WorldTemplateC2ERKNS_19CelestialCoordinateERKSt10shared_ptrINS_17CelestialDatabaseEE+0x216) [0x11f1a26]
./starbound() [0x109c274]
./starbound() [0x109c9ac]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star10WorkerPool11addProducerISt10shared_ptrINS1_17WorldServerThreadEEEENS1_17WorkerPoolPromiseIT_EESt8functionIFS8_vEEEUlvE_E9_M_invokeERKSt9_Any_data+0x26) [0x10b7086]
./starbound(_ZN4Star10WorkerPool12WorkerThread3runEv+0x5f) [0xa8eddf]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x89134) [0x7f83f19c9134]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc) [0x7f83f1a497dc]
Caused by: (AssetException) Error loading asset /biomes/distributions.config:uncommonRandomMFM
./starbound(_ZN4Star13StarExceptionC2EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x66) [0xa91c36]
./starbound(_ZN4Star14AssetExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x52) [0xab4e22]
./starbound(_ZN4Star14AssetException6formatIJNS_9AssetPathEEEES0_PKcDpRKT_+0x1b) [0xab5cbb]
./starbound(_ZNK4Star6Assets8getAssetERKNS0_7AssetIdE+0x10c) [0xab341c]
./starbound(_ZNK4Star6Assets4jsonERKNS_6StringE+0x63) [0xab34d3]
./starbound(_ZN4Star21BiomeItemDistributionC2ERKNS_4JsonEmf+0x5da) [0xb57a0a]
./starbound(_ZNK4Star13BiomeDatabase19readBiomePlaceablesERKNS_4JsonEmf+0x3b1) [0xb4da01]
./starbound(_ZNK4Star13BiomeDatabase11createBiomeERKNS_6StringEmff+0x5aa) [0xb4e86a]
./starbound(_ZN4Star11WorldLayout11buildRegionEmRKNS0_12RegionParamsE+0x3a6) [0x1165746]
./starbound() [0x1169cd9]
./starbound(_ZN4Star11WorldLayout8addLayerEmiiRKNS_6StringENS0_12RegionParamsES4_NS_4ListIS4_SaIS4_EEES7_NS_6VectorIfLm2EEES9_+0x20b) [0x116a5fb]
./starbound() [0x116ba3a]
./starbound(_ZN4Star11WorldLayout22buildTerrestrialLayoutERKNS_26TerrestrialWorldParametersEm+0x16b) [0x11705eb]
./starbound(_ZN4Star13WorldTemplateC2ERKNS_19CelestialCoordinateERKSt10shared_ptrINS_17CelestialDatabaseEE+0x216) [0x11f1a26]
./starbound() [0x109c274]
./starbound() [0x109c9ac]
./starbound(_ZNSt17_Function_handlerIFvvEZN4Star10WorkerPool11addProducerISt10shared_ptrINS1_17WorldServerThreadEEEENS1_17WorkerPoolPromiseIT_EESt8functionIFS8_vEEEUlvE_E9_M_invokeERKSt9_Any_data+0x26) [0x10b7086]
./starbound(_ZN4Star10WorkerPool12WorkerThread3runEv+0x5f) [0xa8eddf]
./starbound(_ZN4Star10ThreadImpl9runThreadEPv+0x15) [0xa9b845]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x89134) [0x7f83f19c9134]
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc) [0x7f83f1a497dc]
[20:21:01.289] [Info] UniverseServer: Warping player 1 to CelestialWorld:558995760:787755344:-133702543:4
[20:21:01.289] [Info] UniverseServer: Warping player 1 failed, invalid world 'CelestialWorld:558995760:787755344:-133702543:4' or world failed to load
[20:21:01.890] [Info] UniverseServer: Clearing broken world CelestialWorld:558995760:787755344:-133702543:4`

**Comment by edwardspec** [comment]
> `biomes/distributions.config:uncommonRandomMFM`

Unrelated to FU (caused by some other mod), FU doesn't have this in any of its biomes.

**Comment by kizeren** [comment]
Ok thanks!  Will continue trying to locate the problem.
