### ISSUE TITLE
Make hostile monster evolutions hostile too

### ISSUE THREAD

**Issue by AlbertoRota** [sayterdarkwynd/FrackinUniverse#374]
# Problem:
After evolving, if not specified, monsters will be 50% of the times aggressive, 50% passive.

# Solution:
After the last **Golemancer core** update, (Already included in this mod), you can pass parameters to monster evolution.
So, for agresive monsters:
```` JSON
"monsterSpawn" : {
    "type" : "monsterType",
    "parameters" : {
        "aggressive" : true
    }
}
````

And for pasive ones:
```` JSON
"monsterSpawn" : {
    "type" : "monsterType",
    "parameters" : {
        "aggressive" : false
    }
}
````

**Comment by sayterdarkwynd** [comment]
correction made. thnks
