### ISSUE TITLE
Explosives break in explosions.

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#377]
This is intentional to avoid lag.
An alternative solution would be to create a remote detonator item that detonates all explosives. And make them wired. We can still blow them up the old way. But the detonator would serve for large scale projects.

**Comment by sayterdarkwynd** [comment]
i suggested a trigger a while back. Arc was supposed to deal with it...but he vanished.

**Comment by Tamamo89** [comment]
I'll be working heavily on this today. Get that done.
