### ISSUE TITLE
limit rampant bee population spawns

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#384]
from Gaikotsu:

Would it be feasible to add a script to the bee monstertype that would put a limit on how many can be spawned within a certain radius? Something like this maybe?

function update(dt)
--get bees within range
local bees = world.monsterQuery(entity.position(), 20, {includedTypes = "bee"})

--count bees within range
local count = 0
for _ in pairs(bees)
count = count + 1
end 

--population control
local deathChance = 0.1
if count > 10 and math.random() < (deatchChance + (0.05 * (count-10))) then
--kill this entity
end
end

**Comment by Kaithos** [comment]
Gaikotsu here: 

Upon further thought, it occured to me that it would likely be easier to prevent spawning if there are already some number of bees within a certain area. 

But I also kind of like the idea of bees "dying" if there are too many for a given area.
