### ISSUE TITLE
create a shit-ton of damage types to correspond to FU effects

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#408]
lets branch out from a few elemental types into many 

not quite sure how yet, but i think its a necessity at this point

needs: 

damage numbers
particles
animations
effects
damageKind

**Comment by Tamamo89** [comment]
I've been thinking of this myself. We could have a bunch of fun with this.
A perfect example would be converting some (not all) of the bee weapons over to bee sting as a status effect.
