### ISSUE TITLE
mantizidrapedchest.recipe outputs an incorrect item

### ISSUE THREAD

**Issue by FullOfSpiders** [sayterdarkwynd/FrackinUniverse#413]
My apologies if I'm violating protocol by posting this here.

In "recipes/ff_stations/clothingfabricator/mantizidrapedchest.recipe", I believe line 7 should be changed from

      "item" : "mantizidrapedlegs",

to

      "item" : "mantizidrapedchest",

Thank you all for your work on this fantastic mod.

**Comment by sayterdarkwynd** [comment]
thx. will fix that up soon
