### ISSUE TITLE
Separate Gas Status Effects

### ISSUE THREAD

**Issue by Tamamo89** [sayterdarkwynd/FrackinUniverse#416]
Explanation: GasImmunity allows you to swim in gasses due to it blocking the liquid friction the various statuses inflict on the player.

We're going to have to go the lava route and have them inflict two status effects. One to manage liquid friction another for the actual status effects such as helium 3s light effect.

**Comment by sayterdarkwynd** [comment]
could wenot just remove the "swimming" status effect? or do some not have that ?
