### ISSUE TITLE
Ocean planet surface dungeons still spawning

### ISSUE THREAD

**Issue by sargon14** [sayterdarkwynd/FrackinUniverse#431]
Hey, I asked about this on the Steam comment thread a week or so ago---I have been noticing that certain surface dungeons are spawning on Ocean planets, which I don't think is desired behavior. I just want to note that I'm still seeing this problem, even though I started a new universe on 11/1 (previously we hypothesized that the problem was fixed in the 10/12 update).

To get more specific: I just found an Ocean planet with the scifidungeon and floranhell dungeons spawned on it. The latter is particularly unsuitable for ocean planets, because it floods from the gaps in the windows!

My best guess is that the problem lies with lines 251-256 of terrestrialworlds.config.patch. Perhaps what's happening is that these defaults are getting merged with the planet-specific dungeon lists, instead of getting overwritten. At this point, since that set of dungeons has been added to most of the planet types manually, I think the way to fix this might be to comment out lines 251-256...

**Comment by sayterdarkwynd** [comment]
yes. Or you could realize that while not perfect for the biome, they add variety and therefore it *is* intentional. But desired, no. 

I'll remove it simply to stop you nitpicking it any further. I have bigger fish to fry lol.
