### ISSUE TITLE
Softcrash to ship in snow biomes (Solved)

### ISSUE THREAD

**Issue by Vakothu** [sayterdarkwynd/FrackinUniverse#435]
After tracing it back, the cause is in FrackinUniverse/biomes/surface/snow.biome.patch , one of the creatures in the pool is "fupolarbearcriter" instead of "fupolarbearcritter"

**Comment by deadsurgeon42** [comment]
Same typo present in `FrackinUniverse/biomes/surface/arctic.biome.patch`

**Comment by Vakothu** [comment]
fixed in commit 7cd2ed6
