### ISSUE TITLE
Weapon Balance discussion

### ISSUE THREAD

**Issue by aztectornado** [sayterdarkwynd/FrackinUniverse#445]
Admittedly, I've always felt like Frackin' Universe is a Endgame+ mod, like everything in it is more challenging and spread out than the base game's linear progression track.

Which is why as I play again, I find it disheartening to see that pretty much every weapon on the list, upgraded or not, struggles to even compete with even the basic crafted weapons of the tier it'd take to get them, or at the very least, the time investment needed to create them. (Especially since you can't just buy FU ores and cheese your way out of hunting for them)

Now, I'm not just complaining to complain, I'd rather discuss this. I can (probably) help out on some of this since it's just changing values, but I wanna know

Should FU weapons be stronger, weaker, or about the same as vanilla weaponry of roughly equal tier? If there should be a difference, about how much should it be?

**Comment by sayterdarkwynd** [comment]
except that you are *dead* fucking wrong about them being weak compared to vanilla.

They follow the same damage algorithm, and are tiered appropriately for the gear/ores they require. In most cases, anyhow. Some could use re-locating into other tiers or new recipes.

What you need to do is wise up and stop using DPS as the sole determining factor of a weapons worth. By doing so you omit the AoE, DoT or special effects most FU weapons have. Not to mention their special basic attaks in some cases (such as applying bleed or shadow bonus damage). Plus with the new Critical Attack system in place, every single weapon in the game now has more reasons to choose them based on your playstyle.

I am done to death arguing about "weak" weapons that literally utilize the same basic limits of all vanilla scripted weapons. I went through their files, copied the low, mid and high end damages to a list, and use that for reference for every weapon i design. In some cases the base damage is lower but the speed is much higher, or they have more knockback, etc. 

You can go ahead and compare, and you will see that I am accurate in this, by simply comparing to the vanilla weapon damages.

**Comment by Tamamo89** [comment]
Hell the bee spear is one of the best spears out their but is incredibly how to find, i wander how many people have actually gotten the blueprint and crafted that shit.

**Comment by aztectornado** [comment]
Woah, shit, I'm sorry. I didn't realize this was such a point of contention for you. 

Admittedly yeah, I was just going by the dps stat when I looked at this. I didn't realize a lot of those effects were present because I was mostly going by what I could see at a glance, and what I saw made me wonder just how effective it really would be to sink time into them if that's all they were. I'd thought about trying to find some standardized way to test each weapon on AoE and longevity situations after tweaking, but I suppose I should have tested them before I even raised my hand. 

I just remember in my last playthrough, at endgame I finally started making some of the FU weapons and found them to be less effective than any of the random rocket launchers I'd found, or so on. As I played this latest one, I found myself comparing stats and kinda afraid to sink time into making any of them, even prior to endgame, which was why I raised the question.

Again, sorry about speaking out of turn like that, I'd just thought that maybe this was a section that got looked over during the conversion to 1.0 or something like that. Lost feature or what have you.

**Comment by IsaacHart** [comment]
shortspears r op

**Comment by sayterdarkwynd** [comment]
No, its all good. You're at least being realistic about it, and trying to weigh in base calculations. Most just play it by ear.


But yea, many FU weapons are designed very specifically for a particular playstyle.

spawn yourself a minirocketlauncher2 and you'll see what I mean about listed stats versus actual effectiveness. You probably won't WANT another weapon after using it, honestly. 

Next, take a look at spawning  hailstrike   . Again, listed stats versus actual effectiveness...very different.

next, take a look at mobiusrifle

now, take a look at  fuaegisaltminigun    (turn off admin mode when firing this one or it wont work as intended...it has special scripting that increases its speed as it fires and alters power and accuracy, etc)


its all a matter of trying them out. Comparing base stats is no way to test a weapon. One could argue "why take a 9mm over a Desert Eagle...clearly the power of the Desert Eagle is higher" but recoil is a bitch and could break your wrist if you're stupid with it :) 

Situation and capability are more important. Part of the issue, I'll grant, is that the weapons base UI doesn't provide room for both stats *and* description text. This means all you have to *go* on is stats. No one can really be faulted for seeing everything through that lens :)

**Comment by sayterdarkwynd** [comment]
as for shortspears... they don't seem OP to me. Reach is drastically reduced from what it was and their damage isn't too extreme. That said, they do still need some tweaks. Perhaps a more educated post than "they r op" would help.

What makes them OP, and how would you suggest correcting it?

**Comment by IsaacHart** [comment]
sorry, my sense of humor is heavily influenced by memes

**Comment by sayterdarkwynd** [comment]
fair enough. Still doesn't answer the question though lol. Are you actually saying they are OP, was it sarcasm and you're saying they are too weak, or ?

**Comment by IsaacHart** [comment]
neither of those things, they are great :)
