### ISSUE TITLE
Add Shadow Taint to Elder/Shoggoth armor immunities

### ISSUE THREAD

**Issue by aztectornado** [sayterdarkwynd/FrackinUniverse#447]
I personally kinda find it funny that the Flesh Cultist gear can withstand Aether sea's Shadow taint, but Shoggoth/Elder armors can't. Kinda the opposite of what you'd expect; superior armor would protect against it, but the inferior might not...

Or is this intended, like how those armors can't protect against Insanity, either?

**Comment by sayterdarkwynd** [comment]
sorta both. Was doing a test-run with the shadow effect first to see how it all stacked out. This shall be done, however. I'd honestly forgotten all about it.
