### ISSUE TITLE
Item Networking Error

### ISSUE THREAD

**Issue by roman-yakobnyuk** [sayterdarkwynd/FrackinUniverse#535]
Good day!

I encountered this error while trying to build item network:

It is impossible to connect terminal to chests that are located more then one wire distance away (not sure how much is it exactly). Even with the use of repeaters, they are not taken into account. Connected terminal wont display items from chests that are further then direct wire connection.

I hope I am explaining clear enough. For example, if maximum wire distance from one node to another is 40 tiles, and I place terminal 60 tiles away from the chest with items, and place repeater 30 tiles away from both chest and terminal to connect them - terminal wont be able to display items from this chest, because they are further then 40 tiles away from each other, thus rendering repeaters useless. 

I also tried to use repeaters from wiring station, not just item network ones, no use anyway. 

Hope you can patch it soon! =) 

Thanks for the great mod.

**Comment by ShaneCourtrille** [comment]
But you CAN move items through the routers to a closer chest and then connect a terminal to that chest as normal.

**Comment by Kherae** [comment]
I'll be honest, I havent had any issues with terminals yet as I haven't had to deal with those issues yet. I'll poke around.

**Comment by Kherae** [comment]
confirming that it's an issue. unfortunately, there's not all that much I can do about it without adding additional load and increased delay to teh code. maybe when I'm in less a lazy mood. can't use world.objectAt in an interface pane, nor world.regionActive...
