### ISSUE TITLE
Anti-Grav Generator

### ISSUE THREAD

**Issue by roman-yakobnyuk** [sayterdarkwynd/FrackinUniverse#537]
Good day,

Another issue is the way anti-grav device operates currently.
If activated inside the building, it prevents any way of travelling down, including grapling hooks and ropes which are unable to be shot. This behaviour is inconsistent with 0G asteroids, where it is possible to shoot grappling hook and items are slowly falling towards the ground. 

In my opinion, anti-grav device should produce very low gravity as opposed to none at all. Same amount of gravity as some easy asteroids, that are not completely 0G. At least, when I was first building it, I expected similar behaviour. I cant see any possible uses for current behaviour except as a trap. 

Thank you!

**Comment by Kherae** [comment]
inability to fire grappling hooks etc....weird, I'm pretty sure I nixed that change. Well, I'll be finishing up my gravity revamp soon, so I'll take a look at that before submitting the pull request

**Comment by Kherae** [comment]
well, just checked. don't know what version you're on, but it definitely isn't the same one I'm on. antigrav gen works well. nanotether working while under the effects. So either I fixed it and forgot (and thus, wait for an update), or you need to update (anyways). Still need to do some fine tuning though...damn field keeps cutting out
