### ISSUE TITLE
nightarancientblade.animation

### ISSUE THREAD

**Issue by Katorone** [sayterdarkwynd/FrackinUniverse#539]
[Error] Exception caught loading asset: /items/active/weapons/nightar/nightarancientblade/nightarancientblade.animation, (AssetException) Could not read JSON asset /items/active/weapons/nightar/nightarancientblade/nightarancientblade.animation

nightarancientblade.animation is located in /items/active/weapons/melee/broadsword/densiniumsword

**Comment by sayterdarkwynd** [comment]
danka
