### ISSUE TITLE
Unlimited Spout

### ISSUE THREAD

**Issue by zyxifrash** [sayterdarkwynd/FrackinUniverse#540]
If the liquid level is near the new spout level, it spawns the liquid without decreasing the spout inventory. If the inventory item is removed at that point, the liquid contains to spawn.

If the liquid under the spout is removed in some other way so the level drops enough, the spout stops spawning.

If this happens, when the same liquid is added back to the spout inventory, the count is reduced quickly without any liquid spawning for a time - suggesting an internal, undisplayed inventory counter was reduced to below zero - until the counter "catches up" and the liquid spawns once more.

![image](https://cloud.githubusercontent.com/assets/25868617/23095500/9eb6684a-f5d8-11e6-847a-d62677e033ec.png)

**Comment by sayterdarkwynd** [comment]
thanks. we'll take a look.

**Comment by Kherae** [comment]
will be fixed reasonably Soon(TM)

**Comment by Kherae** [comment]
it'll be fixed in the next update.
