### ISSUE TITLE
Item Network/Refrigerated Storage

### ISSUE THREAD

**Issue by zyxifrash** [sayterdarkwynd/FrackinUniverse#541]
When extracting perishable food from a Growing Tray and dumping it into a (for example) Food Locker, the items don't stack automatically, even when the decay timer is full. This results in the storage filling up with small stacks of identical items which should have been stacked. Non perishable items stack as expected.

They can be manually stacked which proves the decay timer to be the same.

**Comment by sayterdarkwynd** [comment]
vanilla foods dont stack by default. This is behaving as it , technically, is supposed to. 

If you have a food-rot mod, that's another matter entirely. And not one FU addresses.

We'll see if there is a way around it on the object itself, but don't be too optimistic.
