### ISSUE TITLE
FU missions

### ISSUE THREAD

**Issue by Ragerock** [sayterdarkwynd/FrackinUniverse#544]
I understand everything is meant to be figured out on our own and discovered by poking around in different worlds, but getting to the frozen wastes is way too unclear, I understand there used to be a set line of quests to get this mission from an older build, could this be a bit more streamline? Exploration and discovery are good, but missions to me seem more like a core component and should have a bit more direction to them. At the very least could one of the books hint at what's needed to trigger it? I like it to be difficult more so then unreachable.

**Comment by sayterdarkwynd** [comment]
the point is to get you through most of the hard progression before even presenting you with the option. This is a t6-t8 mission. I don't want people trying it at low tier and getting buttfucked and never going back.

That said, I do plan to change how it is obtained. For now, this is fine until I can revisit it.
