### ISSUE TITLE
Hand Mill - Guide Description

### ISSUE THREAD

**Issue by Sytarks** [sayterdarkwynd/FrackinUniverse#547]
The Frackin'Universe Guide available at the beginning of the game stated that you can craft a hand mill at a machining table, however, the object itself can only be craft at the forging table, requesting a rewrite of the guide cause finding the hand mill spend me quite awhile.

**Comment by sayterdarkwynd** [comment]
quite a while? there are only a few stations at that point in the game....not that long.

but yes, should be corrected. thanks.
