### ISSUE TITLE
[Request - progression] Wiring Table

### ISSUE THREAD

**Issue by Katorone** [sayterdarkwynd/FrackinUniverse#554]
Not sure if this is the right forum to ask this, but here goes.

What do you think about making the wiring table available earlier in progression?  I usually build a base on the starter planet while I'm building up my spaceship.  Having (some) logic available earlier, before durasteel, would be great.  I'm mostly thinking about some basic levers and switches.  I'm perfectly happy waiting a bit longer for the more intricate stuff like gates.

Thanks for reading.

**Comment by sayterdarkwynd** [comment]
i actually see no reason it couldnt be at this point now that the Wrench is a thing. the majority of objects on that station are gated behind durasteel and other tiered goods already.


not sure on requirements for crafting the switches. usually i admin those in. do they use pre-dura materials?

**Comment by Katorone** [comment]
There are different styles of switches.  In vanilla there's one switch craftable with iron, nine with tungsten, one with titanium and one with durasteel.

The defence turret requires durasteel, so it stays gated.
