### ISSUE TITLE
Error due to a missing .weaponability file.

### ISSUE THREAD

**Issue by Boggart** [sayterdarkwynd/FrackinUniverse#574]
The file referenced [here](https://github.com/sayterdarkwynd/FrackinUniverse/blob/45daeb16779e97c14b86933307da1bf3b0c3f3d5/items/buildscripts/weaponabilities.config.patch#L151) is missing and is causing the affected player to crash upon seeing an npc with a generated weapon using the file.

**Comment by sayterdarkwynd** [comment]
thnak you. that one was vexxing me. Did not notice the missing file.
