### ISSUE TITLE
Terminals seem to have a max range that isn't extended by repeaters and doesn't match wiring distance.

### ISSUE THREAD

**Issue by Boggart** [sayterdarkwynd/FrackinUniverse#604]
If a terminal is too far from the attached storages, it'll stop seeing the contents of some of them (probably the further ones) regardless of repeaters or watchers.

There were some items that I couldn't get to show up in the terminal so I tried placing another one, by coincidence this one was very close to the attached storages and it could see all the items so I moved the other one closer and it began working as well, so I moved it back and the problem returned.

The distance they begin to stop working properly under is less than the max wiring distance without repeaters.

**Comment by Kherae** [comment]
1) you're exactly right.
2) it's been brought up before
3) Not fixing it in the foreseeable future.
