### ISSUE TITLE
Constant sulphuric atmos spam despite protection.

### ISSUE THREAD

**Issue by Boggart** [sayterdarkwynd/FrackinUniverse#605]
You get repeatedly spammed with the sulphuric atmosphere warning despite being immune to it.

**Comment by sayterdarkwynd** [comment]
with what build? ive made a TON of changes to planetary biome effects. Are you using the github build? if so, thats stuff from the new implementation and might be the reason. I'll give it a look soon.

**Comment by Boggart** [comment]
Forgot to mention, this is on 5.0.235.

**Comment by sayterdarkwynd** [comment]
yea, there was a mixup there. wasnt my doing, but another on the team. was reading "sulphuricImmunity" but should have been "sulphuricimmunity"

will be fixed on the github build momentarily
