### ISSUE TITLE
Pumps have an unused fuel slot and compression wiring point.

### ISSUE THREAD

**Issue by Boggart** [sayterdarkwynd/FrackinUniverse#606]
Seemingly a leftover from Steambound, pumps have an unused wiring input for "compression" that doesn't seem to be needed and tends to confuse players. It also has a slot marked fuel in the interface that doesn't seem to be used except to also store pumped liquid.

**Comment by sayterdarkwynd** [comment]
fuel is planned. we're pinned by other stuff right now.
