### ISSUE TITLE
General organization of craftable items

### ISSUE THREAD

**Issue by rahlzel** [sayterdarkwynd/FrackinUniverse#61]
(I followed the wiki's Github link which was to the FrackinUniverse_RC version, so I'm moving it here to the correct repo)

This has been a thing since I used FU a year ago, and I figured the chaos of it would make it a pretty high priority to be fixed, but there might be a reason behind it that I don't fully understand.

Craftable items are all over the place - 

- Shields are in the Clothing Fabricator and the Armory
- Armor is in the Clothing Fabricator
- Mining Lasers in the Matter Assembler and the Nanofabricator
- The DNA symbol (http://i.imgur.com/PlhgQmj.png) that the player first identifies as the category with which to build crafting stations is also used for accelerator gels in another station and cell material in yet another.
- DNA samples and Mineral samples are separated between two categories in the Bio-Chem lab despite them having the same name and icon.
- Magnesium Sulfate in the Fission Furnace and in the Bio-Chem Lab
- Ammonium Sulfate, Phosphorus, Saltpeter, Magnesium Powder in the Fission Furnace and not where all the other powders are in the Bio-Chem Lab
- The "Shield" category is in 4 different crafting tables, two of which are empty
- Ore that's made in both Fission Furnace and Bio-Chem lab

This is just a few examples. I've only (in this playthrough) made six out of the how many crafting tables? A dozen maybe? This is really an amazing mod - the amount of content here is awesome, but damn it's unorganized. Me having an OCD personality doesn't help, either. It's almost frustrating to the point of quitting, but I thought I'd try a different approach.

Is this a planned fix, or is it something you'd like some help with? I've been using Git for several years and though I'm not overly familiar with LUA, I'm very familiar with programming in general. Do you have a plan on how you'd like the crafting stations to work progression-wise, and an idea on where you think similar items should belong?

**Comment by sayterdarkwynd** [comment]
Non-metal shields are in the Clothing Fab. Same with armors. 

Mining Laser base appears in the MA. The upgrades appear in the Nano, which is effectively an Upgrade station.

crafting station icons were kept generic out of laziness. one day ill correct them lol

Gene / Mineral samples can probably be moved together , and ill do that now.

Magnesium Sulfate is fine. It's suppsoed to be in two places so people have options.

I'll add those other powders to the chemlab as well, perhaps


generally if something is in more than one table it is 100% intended to be that way.



Now, that said, if you wanted to take a crack at reorganizing things, feel free. It might be better than how I have it laid out.

**Comment by rahlzel** [comment]
I realize you've closed this which is fine, there's just another few things I wanted to mention.

My overall point to this issue report is that you've changed several "rules" about how the default game works, which has an adverse effect on new-user experience. For example, the default Sewing Machine only has cosmetic items (http://i.imgur.com/AhKgAMT.png). The Clothing Fabricator is obviously meant as an addon to clothing, yet there's only armor in it, so there's now two places where people are looking for armor. Furthermore, several of the non-metal armors in the Clothing Fabricator use metal to construct them. And on the shields - it feels like separating them because they're not metallic is too specific. It's much nicer to click once and see all options than to click several times to see/compare them all. Though it seems silly, the default game puts their shield in with weapons in order to minimize item-hunting as much as possible (and because there's only one damn craftable shield: http://i.imgur.com/moHZV2S.png).

Another "rule" (I can't think of a better term here, there might be one) of the default game is that manufactured bars from ore don't change their quality level: http://i.imgur.com/p2YsUPx.png. Common ore becomes common bars, rare ore becomes rare bars, etc. A few of your ores/bars don't do this: http://i.imgur.com/phka2eU.png or they reverse direction: http://i.imgur.com/zvrBQ19.png

I hope I'm not sounding overly critical. This is an immense mod and there's hundreds (maybe thousands?) of new materials to keep track of, so what you've got thus far is awesome. There's just a few nitpicky areas to improve on if you're as OCD as I am :)

If you're interested, I'll write up a quick prototype of how I'd organize the crafting materials in each station to give you a better idea of what I mean.
