### ISSUE TITLE
Game freezes when taking damage from wasps for the first time.

### ISSUE THREAD

**Issue by Pyrolusite** [sayterdarkwynd/FrackinUniverse#62]
After the "Sting" debuff has been applied for the first time however, it no longer happens.

**Comment by renbear67** [comment]
Could you please provide a log file file from when this happens to you? It's probably generating an error.

**Comment by Pyrolusite** [comment]
Found the error in the log : http://pastebin.com/vn6FHGv2

**Comment by sayterdarkwynd** [comment]
for the love of god. stop reporting issues that were fixed in a previous build. issue fixed and closed.

**Comment by Pyrolusite** [comment]
I'm sorry, I downloaded the last "release" build instead of the content of the repo directly.

I'd suggest writing it somewhere on your Chucklefish Forum post, for those who don't use the steam workshop, so that it doesn't happen again.
