### ISSUE TITLE
Radioactive bees do not spawn?

### ISSUE THREAD

**Issue by UberWaffe** [sayterdarkwynd/FrackinUniverse#624]
After being unable to find radio-active bees in the game (expected in irradiated biomes) I took a look at the biome spawn profiles.
It appears there is no biome that radioactive bees spawn in.
Checking the bee breeding files I also could not see a way to breed radioactive bees.

Ended up adding radioactive bee spawning to irradiated biomes to get around this.

Possible bug? Or did I just miss another path to getting them?

**Comment by sayterdarkwynd** [comment]
not a bug. they dont spawn in the wild. You need to breed them.
