### ISSUE TITLE
(ItemException) No such item 'bolbohnseed'

### ISSUE THREAD

**Issue by mrawesome1337** [sayterdarkwynd/FrackinUniverse#626]
![image](https://cloud.githubusercontent.com/assets/4985581/24581097/8e4a856a-16c9-11e7-96a8-faa3b03013e1.png)

I took a screenshot of the exception. Whenever I open the botany lab I receive this error. I was unlocking some tech so I imagine that this seed became available. I do have more than frackin' universe installed. Below you can find a screenshot of my subscriptions through the steam workshop. None of these mods include new items. (Weapon Stats and Improved Containers).

I am delving into the logs file now. I'll leave a snippet. Maybe I'll get some research in and I'll leave some additional information. It looks like this file was updated today. I saw that the mod was updated today in steam workshop. You may have broken it.

`[10:48:49.126] [Error] Exception caught loading asset: /objects/farmables/bolbohn/bolbohnseed.object, (AssetException) Could not read JSON asset /objects/farmables/bolbohn/bolbohnseed.object`

**Comment by mrawesome1337** [comment]
/objects/farmables/bolbohn/bolbohnseed.object has a duplicate key "largeImage"

Would that cause this not to load?

**Comment by guidez** [comment]
https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/objects/farmables/bolbohn/bolbohnseed.object

Key "largeImage" IS duplicated. Funsies.

```
  "inventoryIcon" : "bolbohnseedicon.png",
  "largeImage" : "bolbohnseed.png:default.3.0",

  "tooltipKind" : "seed",
  "largeImage" : "bolbohnseed.png:default.2.0",
```
