### ISSUE TITLE
aimedprojectile.lua incorrect variable used?

### ISSUE THREAD

**Issue by UberWaffe** [sayterdarkwynd/FrackinUniverse#627]
[aimedprojectile.lua#122](https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/items/active/weapons/staff/abilities/aimedprojectile/aimedprojectile.lua#L122)

Line for `world.spawnProjectile` uses `param`, but there appears to be no such variable.
The variable defined just above [aimedprojectile.lua#117](https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/items/active/weapons/staff/abilities/aimedprojectile/aimedprojectile.lua#L117) is `pParams`

Found while mucking around with weapon stats. Using aimed projectile did not seem to apply weapon level correctly. Changing the variable from `param` to `pParam` seemed to fix this.

The current `param` does not throw any errors in the starbound logs though.

**Comment by sayterdarkwynd** [comment]
thx
