### ISSUE TITLE
Typo/lacking punctuation in some descriptions.

### ISSUE THREAD

**Issue by Pyrolusite** [sayterdarkwynd/FrackinUniverse#63]
![image](https://cloud.githubusercontent.com/assets/6333186/17219700/9025f742-54ec-11e6-8b80-469befad4ec1.png)
![image](https://cloud.githubusercontent.com/assets/6333186/17219746/be676bea-54ec-11e6-8a96-88964eebcf41.png)

**Comment by sayterdarkwynd** [comment]
Nothing wrong with the Perfect For Casting one. It's a reference to casting-couch porn.

the first will be fixed in a moment.
