### ISSUE TITLE
Magma bees

### ISSUE THREAD

**Issue by HentotheWen** [sayterdarkwynd/FrackinUniverse#638]
Not fully implemented:
- Do not sting yet
- Magma frame and magma honey jar need to be implemented
- Needs extractor/ industrial centrifuge recipes

**Comment by sayterdarkwynd** [comment]
they arent going to sting

magma honey isnt needed. magma give hot honey already

already has extractor/centrifuge recipes here on github


You are not the judge of what is, and isn't , fully implemented. I understand helping out, but you have no idea what I planned with magma bees.
