### ISSUE TITLE
Power output does not match description

### ISSUE THREAD

**Issue by HentotheWen** [sayterdarkwynd/FrackinUniverse#639]
At first I thought this was intended, but with most recent patch setting quantum/elder fluid combo to exactly 128 it does not seem so.

In my game I get extra power from several power sources that I have tested:
Regular solar panel - generates up to 2.666 power instead of 2 listed.
Solar tower - generates around 12 power instead of 9 listed
Quantum Reactor - before the recent patch, I got an extra 20 power out of this compared to the fuel list with every kind of fuel.  After the recent patch, I am still getting that extra 20 power.  For example, Solarium is 100 instead of listed 80, and elder fluid shows !!! on the power meter which normally maxes out at 128.

**Comment by sayterdarkwynd** [comment]
2.6666?  honestly? 2 is fine.

tower:   "over 9u!"     not  "9u", so technically its fine. But I'll update it so you dont report it again lol.

quantum reactor is fine. The readout topping out on the power reader is a bit annoying though. Guess I'll need to tinker to get it just right.
