### ISSUE TITLE
Atmosphere regulator

### ISSUE THREAD

**Issue by HentotheWen** [sayterdarkwynd/FrackinUniverse#640]
This signature item of FU has not kept up with the recent weather changes.  It only handles passive damage debuffs.  

That means lightning, sandstorms, acid storms, etc. get through.  Maybe it doesn't make sense to protect vs. insanity, and may not be intended to protect against tile effects e.g. grav/molten/poison rain.  But if NPCs and monsters are coded to resist the various "storm" effects the player should get the same benefit.

**Comment by sayterdarkwynd** [comment]
false.



  {{stat = "breathProtection", amount = 1},
   {stat = "waterbreathProtection", amount = 1},
   {stat = "protoImmunity", amount = 1},
   {stat = "waterbreathProtection", amount = 1},
   {stat = "breathProtection", amount = 1},
   {stat = "biomeradiationImmunity", amount = 1},
   {stat = "biomecoldImmunity", amount = 1},
   {stat = "biomeheatImmunity", amount = 1},
   {stat = "sulphuricImmunity", amount = 1},
   {stat = "sulphuricImmunity", amount = 1},
   {stat = "ffextremeheatImmunity", amount = 1},
   {stat = "ffextremecoldImmunity", amount = 1},
   {stat = "ffextremeradiationImmunity", amount = 1},
   {stat = "pressureProtection", amount = 1},
   {stat = "gasImmunity", amount = 1},
   {stat = "extremepressureProtection", amount = 1}})




all of those are blocked by the atmosRegulator. The new weather effects shut off if any of those are present. Should work fine. Not seeing how this is an issue.

**Comment by HentotheWen** [comment]
FrackinUniverse/stats/effects/fu_weathereffects/new/electric/electricweathernew.lua

	if status.statPositive("biomeelectricImmunity") or world.type()=="unknown"  then
	  deactivateVisualEffects()
effect.expire()

I did not see electricity protection.  The planet I am on has crystal storm and severe crystal storm, not sure if they are considered electric.
