### ISSUE TITLE
nonexistant npctype added to villagers graduation table

### ISSUE THREAD

**Issue by ThreeTen22** [sayterdarkwynd/FrackinUniverse#646]
Hi there!

I was testing out possible crewmembers that graduated from villagers and it seems like one of the npctypes provided is called "crewmemberscientist1", which throws an error saying it doesn't exist.  I poked around and it seems like this was a change from the most recent update.

It doesn't look like the tenant helper script checks for whether npctypes exists when graduating so this would probably cause some issues.

**Functions:**
 tenant.graduate() ->tentant.setNpcType() 
found in _/scripts/tenant.lua_

**Comment by sayterdarkwynd** [comment]
thanks. typo . Not from the most recent update though. That's been there fore quite a bit. Still, easily corrected.

**Comment by ThreeTen22** [comment]
hey sorry to bring this up again, but it doesn't look like the faulty npctype was actually removed.
