### ISSUE TITLE
Shared inventory / buff icons

### ISSUE THREAD

**Issue by HentotheWen** [sayterdarkwynd/FrackinUniverse#648]
Atmosregulator and atmosregen have the same inventory icons.  I couldn't even locate the .object file for the regenerator.

Atmosregulator, gravgen, and antigravgen have the same buff icons.

I am sure I must be exasperating Satyr with this nitpicking.

**Comment by sayterdarkwynd** [comment]
yes, they do have the same icon. I also don't care that they have the same icon. feel free to whip up a new one.
