### ISSUE TITLE
Ore Detector not working with FrackinUniverse ores.

### ISSUE THREAD

**Issue by Pyrolusite** [sayterdarkwynd/FrackinUniverse#65]
Everything is in the title.
To be fair though, it doesn't detect Coal either on an unmodded game, so it's up to you.

**Comment by sayterdarkwynd** [comment]
Talk to the mod author. Not my issue.

**Comment by Pyrolusite** [comment]
Uuuh... It's not a mod. It was added in Starbound 1.0, probably earlier in nightly builds.
http://starbounder.org/Ore_Detector

**Comment by draeath** [comment]
Does it not detect them at all?
See: (stock-assets)/items/active/unsorted/oredetector/oredetector.activeitem

      "pingDetectConfig" : {
        "type" : "ore",
        "image" : "/items/active/unsorted/oredetector/detectnoise.png:<variant>",
        "variants" : 4,
        "colors" : {
          "copper" : [80, 80, 40, 255],
          "silver" : [200, 200, 230, 255],
          "gold" : [200, 180, 30, 255],
          "iron" : [160, 160, 160, 255],
          "tungsten" : [120, 120, 120, 255],
          "titanium" : [255, 255, 255, 255],
          "durasteel" : [90, 90, 200, 255],
          "aegisalt" : [200, 255, 50, 255],
          "violium" : [200, 70, 255, 255],
          "ferozium" : [50, 230, 230, 255],
          "solarium" : [255, 255, 0, 255],
          "diamond" : [0, 0, 255, 255],
          "erchius" : [235, 178, 247, 255], 
          "none" : [120, 160, 120, 50]
        }
      },

Note the "catch-all" at the end still has an assignment. This *should* hit anything that's of type "ore?"

**Comment by draeath** [comment]
Working on a patch now, but I can't say my choice of colors will be the best.

**Comment by draeath** [comment]
Here's a patch that should do the job. Still looking for where the ore colors or artwork is defined, so I can square up the colors better before putting in a pull request with an implementation:

    [
        { "op": "remove", "path": "/pingDetectConfig/colors/none",       "value": [235, 178, 247, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/berlinite",  "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/lazulite",   "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/lead",       "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/magnesium",  "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/mascagnite", "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/moonstone",  "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/neptunium",  "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/plutonium",  "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/sulphur",    "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/thorium",    "value": [196, 196, 196, 255] },
        { "op": "add",    "path": "/pingDetectConfig/colors/none",       "value": [235, 178, 247, 255] }
    ]

**Comment by draeath** [comment]
Pull request is in. Colors chosen /w sampled average of the tile graphics themselves, so they should be appropriate.
