### ISSUE TITLE
Idea for improving atmosgenerator

### ISSUE THREAD

**Issue by HentotheWen** [sayterdarkwynd/FrackinUniverse#650]
Now that I know the way the new weather system works... wouldn't it be possible to shut down all nasty weather effects with the atmosgenerator?  E.g. just inserting a variable check for status.atmosgenerator, if positive, no nasty weather.  I mean stuff like molten metal rain, crystal storm, gravrain etc. that doesn't fit within the new weather/epp resistance system.  IMO total weather immunity is quite reasonable for the most expensive item in the game, by far.  Except for stuff like meteor showers or insanity :)

**Comment by sayterdarkwynd** [comment]
yea, its easy enough to do. havent gotten to it yet. im solo again.
