### ISSUE TITLE
wonky mutagene unlocks/recipes

### ISSUE THREAD

**Issue by dualinfinities** [sayterdarkwynd/FrackinUniverse#651]
a number of items unlocked by the various mutagenes don't use them in the recipes, will put them here as I look them over.
lasher plant, pasaka vine seeds, immunity I augment, do not use potent mutagene required to unlock them. biopistol uses durable mutagene instead of the potent one required to unlock it. potent mutagene is 0 for 4 in terms of unlocks.
wretchel seed does not use powerful mutagene, leaving it 0 for 1.
goregun, eyecannon, lactarius indigo seed do not use the basic mutagene required to unlock them. basic mutagene is 0 for 3.
advanced quantum set, tetherhook seeds, do not use durable mutagene required to unlock them. durable mutagene is 1 for 5.
hopy shit, this is even wonkier than I thought :/

**Comment by sayterdarkwynd** [comment]
a lot of recipes have changed over the years. sometimes things get missed. im one guy.

**Comment by dualinfinities** [comment]
yeah, that's what I was assuming, this didn't seem like something that'd happen all at once.
