### ISSUE TITLE
"Replace" in shiplocker.treasurepools.patch conflicts with mods

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#66]
Your 'shiplocker.treasurepools.patch' file does a "replace" of the entire 'starterTreasure' field. If you're going to do a .patch instead of replace the entire shiplocker.treasurepools file, then why not use "add", instead? The way this was done is rather sloppy and it conflicts with any mod which attempts to alter the 'starterTreasure' field of shiplocker.treasurepools.

For example, the way things are, it conflicts with Better Starting Items:
http://steamcommunity.com/sharedfiles/filedetails/?id=730500326&tscn=1469593682

You have no idea of how much time I spent looking for the cause of this mod conflict!

To fix this issue, 'shiplocker.treasurepools.patch' can be simplified to just this:

[
  {"op": "add", "path": "/starterTreasure/0/1/fill/-", "value": {"item": [ "sciencebrochure", 1]}}
]

**Comment by renbear67** [comment]
Absolutely valid point. I'll see what I can do.

**Comment by renbear67** [comment]
And thank you for the code to fix it!

**Comment by renbear67** [comment]
@sayterdarkwynd , this needs to be closed
