### ISSUE TITLE
"Gargantuan" ship hatch - wiring issues

### ISSUE THREAD

**Issue by damianb** [sayterdarkwynd/FrackinUniverse#664]
Trying to wire the gargantuan ship hatch (lab themed vertical doorway) on a server seems to cause some issues.  Door is toggling between closed and open states rapidly when used with a standard smallwallswitch.

**Comment by Chicken-Nugget** [comment]
Yeah noticed this as well, it actually is opening, just showing closed. Mine is hooked up to proximity sensors. When the sensors open it, it will show open. Next time they open it, it will show open for a split second and then show closed (but it actually is still open, try passing through it, you should be able to). After that it will show open again, then it won't, then it will. It alternates between showing its state correctly, but it is actually always open.

**Comment by sayterdarkwynd** [comment]
forgot this was even here.
