### ISSUE TITLE
labpipe, remove or fix?

### ISSUE THREAD

**Issue by dualinfinities** [sayterdarkwynd/FrackinUniverse#665]
hey, are lab pipes intended to be craftable? b/c the unlock in prototyper.object uses "labpipe" when the block's name is "fulabpipe". I'd heard somewhere that they're being phased out or something? if true the recipe should be removed from the machining table, if not the name should be fixed. dunno what your plan is, so I'm just opening an issue.

**Comment by sayterdarkwynd** [comment]
thx

**Comment by sayterdarkwynd** [comment]
and no, they arent being phased out. I just fuckin added them a few weeks ago lol

**Comment by dualinfinities** [comment]
oh, okay. I thought I heard something of the sort. don't even know where from.
