### ISSUE TITLE
maybe add byproducts to radioactive ores in powered furnaces? they seem boring right now

### ISSUE THREAD

**Issue by dualinfinities** [sayterdarkwynd/FrackinUniverse#666]
this is pretty minor honestly, but having them only having a single output bothers me, in that way things do when just one thing is out of place. do you have any input on this topic, or should I just go figure it out on my own and just come to you with a PR?
EDIT: I got the best issue number, sweet!

**Comment by sayterdarkwynd** [comment]
what? I have no idea what you are even saying, 

The Fission Furnace already *does* that. I see no need to add it to furnaces. You can use the centrifuge to get those byproducts.

**Comment by dualinfinities** [comment]
yeah, I meant arc/blast. sorry for being unclear. I'll be doing that then!
