### ISSUE TITLE
missing bot healing station

### ISSUE THREAD

**Issue by Chicken-Nugget** [sayterdarkwynd/FrackinUniverse#669]
Was trying to figure out how to heal a broken bot pod, no item seems to exist to do this.

I see the code for it at objects/crafting/bothealingstation, but there is no recipe file to make it obtainable. Is it non-functional or was it forgotten? Edit: Spawned it in, functions correctly. Just no recipe.

**Comment by sayterdarkwynd** [comment]
my bad. will add recipe now.
