### ISSUE TITLE
Typo in item type for Ansible Network: Mining Consortium

### ISSUE THREAD

**Issue by MortisLegati** [sayterdarkwynd/FrackinUniverse#68]
I tried to open the aforementioned vendor interface and game exception'd out to the menu with an invalid itemtype error something along the lines of "feroziumorew.ore"

**Comment by draeath** [comment]
Can you attach your starbound.log (found in the "storage" directory)? If not, any chance you have a screenshot of the error?

**Comment by MortisLegati** [comment]
This likely has been fixed on the steam version.  I was getting it to happen reliably earlier and now it's just not showing up.
