### ISSUE TITLE
Species called human even if you aren't (quest)

### ISSUE THREAD

**Issue by Geird** [sayterdarkwynd/FrackinUniverse#685]
In the science facility quest to create a machining table, the players species is assumed to be human, despite in this case being a hylotl.
[Image](http://imgur.com/a/0i1O5)

**Comment by sayterdarkwynd** [comment]
"text" : "You've taken your first steps in Frackin' Universe With the Machining Table you can now branch out into a wide assortment of Lab Stations and Equipment as well as crafting resources Let's start by making 9 copper wire.",
  "completionText" : "Try building a few more basic goods such as a ^orange;coil, circuitboard^reset; or an extremely useful ^orange;Extraction Lab^reset;. ^orange;The Machining Table and its upgrades^reset; are necessary for every FU crafting station  Use it well.",



where is it assumed to be human? it mentions race exactly nowhere.
