### ISSUE TITLE
Healing I EPP Augment: Uncraftable

### ISSUE THREAD

**Issue by MortisLegati** [sayterdarkwynd/FrackinUniverse#69]
The recipe calls for two units of Microchip, which appear to be deprecated.  
Might want to search for instances of that crafting material to clean up any other references to it from cropping up in the future.

**Comment by draeath** [comment]
Pull request is in with the fix. Replaced that input with the same used by the other tier1 augments such as the cold, heat, and radiation protection augments.

**Comment by draeath** [comment]
No other references to this item found - we're probably safe to yank it out but as I'm still very new to Starbound modding, I'd rather not make that call nor set about the task.

**Comment by renbear67** [comment]
I'm fairly sure that was the last one, yes. Thanks, @draeath !
