### ISSUE TITLE
"Exception caught in client main-loop (EofException) Failed to read full buffer in readFull, eof reached"

### ISSUE THREAD

**Issue by TCloudGaming** [sayterdarkwynd/FrackinUniverse#691]
log: https://pastebin.com/23iE20XW

**Comment by sayterdarkwynd** [comment]
yes, and as stated in : CF forums for FU, Steam for FU and the Discord for FU:  The only solution is to delete the offending world file. it will regen on restart. There is no other fix. This is not an FU specific bug.

**Comment by TCloudGaming** [comment]
Would you mind taking a second look, as it seems that the planet generated by Frackin Universe was at fault here. It generated some mobs with avali gear on. We don't have any avali mods installed on the server.

Here's the server log: http://vpaste.net/6hmd3
