### ISSUE TITLE
Aetherium Shortsword broken in multiplayer.

### ISSUE THREAD

**Issue by TCloudGaming** [sayterdarkwynd/FrackinUniverse#697]
Upon trying to equip the short sword in multiplayer I immediately crashed. Subsequent attempts to join multiplayer failed, but I was able to join singleplayer just fine.

Log:  https://pastebin.com/Ztw8WjaD

**Comment by Chicken-Nugget** [comment]
Its not an Aetherium Shortsword error, but instead something with Avali Codexes

[02:59:10.510] [Error] Failed to valid player with uuid dda25df6505d911e8663ed2c6571767f : (AssetException) Error loading asset /player.config:defaultCodexes.avali

I see that the server is not finding avali armor or codexes, and it isn't loading any avali mods, where your single player obviously is. Make sure your server mods are synced with your single player mods.

**Comment by TCloudGaming** [comment]
The mods are in sync. The reason for the avali stuff was I made an avali save file at one point, but didn't delete the save when removing the mod. I have since deleted the save, but the sword still has the same results in multiplayer.

log: https://pastebin.com/SFQXZ09p

**Comment by TCloudGaming** [comment]
[Starbound Server Log..txt](https://github.com/sayterdarkwynd/FrackinUniverse/files/977866/Starbound.Server.Log.txt)
Here's the server log for it as well. It's almost 20mb in size though so.

**Comment by sayterdarkwynd** [comment]
not seeing anything wrong with the weapon. Not overly concerned, as FU isn't designed with MP in mind, in any case. I can look into it more if this happens to more people, but I have no idea why it would do what you are saying.
