### ISSUE TITLE
Frozen Volcanoes are... weird.

### ISSUE THREAD

**Issue by Pyrolusite** [sayterdarkwynd/FrackinUniverse#71]
http://i.imgur.com/jlOoUxR.jpg

Walking on invisible blocks seems weird to me.

**Comment by renbear67** [comment]
He was wondering about this. @sayterdarkwynd ? Was this fixed?

**Comment by sayterdarkwynd** [comment]
that may be the issue. I'll investigate. Looks like its weather-related tiles.
