### ISSUE TITLE
Acid immunity message spam

### ISSUE THREAD

**Issue by Mijyuoon** [sayterdarkwynd/FrackinUniverse#724]
[This](https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/stats/effects/liquidimmunity/sulphuricimmunity.statuseffect#L3) causes the messages about "Acid protection required" to be constantly spammed, even though the status effect itself works fine. Removing it seems to solve the issue.

**Comment by sayterdarkwynd** [comment]
removing it is also not an option. It will otherwise not be naturally blocked as I want.

Not sure why it is spamming, though, since the only message it should give is checked to prevent this. I'll make sure the function works.
