### ISSUE TITLE
Human Bunker NPC Server Crash

### ISSUE THREAD

**Issue by Stormalisk** [sayterdarkwynd/FrackinUniverse#762]
When spotted by a human guard of the USCM Bunker, my character is unable to play without crashing on the server. The error that I was greeted with is "Exception caught in client main-loop (EofException) Failed to read full buffer in readFull, eof reached".

Allow asset mismatches is enabled, but nothing in the pack should be mismatched. Multiple reinstall attempts were unsuccessful, and it only occurred when spotted by that guard.

Full mod list in case of possible confliction causing guard to have the deathcrash stare:
100%bossloot
CompactCrops
ContainerUITweak
CraftableComponents
CraftableSeeds
EverFrogg
FoodStack
FrackinUniverse
GivemeCotton
IlluminatedOres
ImprovedContainers
InstantCrafting
JobOffers
LargerLockers
LargerLockersImproved
PerennialCrops
PixelGoodsStore
PowerfullyUnique
ShipAnything
UnbreakableTeleporters
UniversalUncrafter
WeaponReinforcer

**Comment by sayterdarkwynd** [comment]
planet error. delete that worlds file. problem will go away. 

annoying, but tis the only fix.
