### ISSUE TITLE
Blister armor Mk2 (Again)

### ISSUE THREAD

**Issue by mahorych00** [sayterdarkwynd/FrackinUniverse#779]
Buff is present, but set offers no protection against proto-poison, even though it is stated in description.

**Comment by mahorych00** [comment]
It also seems that this set doesn't provide protection from liquid nitrogen either.

**Comment by sayterdarkwynd** [comment]
{stat = "poisonStatusImmunity", amount = 1.0}
  {stat = "protoImmunity", amount = 1.0},
  {stat = "pusImmunity", amount = 1.0},
  {stat = "liquidnitrogenImmunity", amount = 1.0}


its in the code.

**Comment by sayterdarkwynd** [comment]
ah, i see.....its claiming theres an error.....not seeing it. will investigate.
