### ISSUE TITLE
Farming wells only give 10% of the water they're holding

### ISSUE THREAD

**Issue by aztectornado** [sayterdarkwynd/FrackinUniverse#782]
I'm not sure if this is intentional or not, but when activated, farm wells drop 10 water blocks and drain 100 from their storage count, meanwhile water pumps drop 50 while draining 50 from apparent count; a 1 to 1 ratio. 

Is it intentional that they have different ratios of stored to blocks? If so, wells are nearly useless, even early game, and might be considered for rebalancing.

**Comment by sayterdarkwynd** [comment]
wells do exactly what they are intended to do: provide an early game water source that isn't too great but allows them to get by until they can upgrade it or get the liquid add-on for the MM.

It isn't efficient, and the water difference is set this way on purpose to illustrate that point and encourage upgrading ASAP.
