### ISSUE TITLE
Activating contract of mercenaries in ship causes them to spawn outside

### ISSUE THREAD

**Issue by Sonsalt** [sayterdarkwynd/FrackinUniverse#825]
**Reproduce:**
1. Get new mercenary contract
2. Jump to ship
3. Activate contract
4. Observe mercenary being outside of the ship

This bug prevents the mercenaries to be activated. One can only see the shadows above the ship. 

**Acceptance criteria:** 
When activating contract, mercenary spawns inside the ship so the player can select the NPC

**Comment by sayterdarkwynd** [comment]
uh...no. They spawn where your cursor is. Move your cursor within your ship, and they will spawn within your ship :)
