### ISSUE TITLE
Batteries Share Output Via Inputs on Output Nodes

### ISSUE THREAD

**Issue by Frobob** [sayterdarkwynd/FrackinUniverse#855]
This one's a bit difficult to explain... I noticed that my power readouts were showing as maxed out after the last update, so I set to investigating.
The output node in the example is a relay, but it works on all output nodes I've tested, even the outputs of crafting stations such as the arc furnace.
[http://imgur.com/a/QMWFQ](url)

**Comment by Gaikotsu2** [comment]
This is due to the update to the power system that was pushed today. Power sensors now read total available power from the entire connected graph of objects. In your case, you have a battery that outputs 8 and another that outputs 16 resulting in a network with a total capacity of 24.

**Comment by Frobob** [comment]
What if I need to measure the amount of power coming from a specific part of the network?

**Comment by Gaikotsu2** [comment]
Why would you need to be able to do that? The power system rework makes objects that consume power pull it from anywhere on the connected network it is available (with a preference for non-battery sources first). Under that type of system, total power available to the network is the only useful piece of information.

**Comment by Frobob** [comment]
I realized that after posting that comment, heh.
The new problem is that the 128 limit on the readouts is far too low for them to be used on larger networks. Perhaps remove the display's limit or make a higher-grade one with no limit? (I can stick this in a suggestion thread somewhere if you want)

**Comment by Gaikotsu2** [comment]
I would be willing to bet the only way it will get done is if you make the update and submit a PR. Having a single network that produces more than 128 units of power is pretty rare.

**Comment by shadow-absorber** [comment]
hmmm that could be done but in that case change the issue name @Frobob
