### ISSUE TITLE
Aeroponics and Hydroponics tubes do the same thing

### ISSUE THREAD

**Issue by renbear67** [sayterdarkwynd/FrackinUniverse#89]
... and maybe they shouldn't? Aeroponics Tubes (which are from the Avali stuff) unlock a bit after Hydroponics Tubes. Neither ever require watering. Hydroponics Tubes have assets for a dry version, Aeroetc don't. Maaaaaaaybe we should make Hydroponics Tubes require watering, but leave Aerowhatever the way they are? Also, "hydro" vs "aero" implies it.

**Comment by sayterdarkwynd** [comment]
yea, im cool with that.

**Comment by renbear67** [comment]
I've got the hydroponics tubes drying out properly now. Not sure about the game balance, though, since there's no real reason to use them (other than being more of a science/spaceship aesthetic). Maybe change the recipe to output five tiles for one plastic? (also dirt and I think water)
