### ISSUE TITLE
Incinerator bug: input slot not included in Inventory Network

### ISSUE THREAD

**Issue by VerisZG** [sayterdarkwynd/FrackinUniverse#902]
Hey, quick bug(?) report.
Item Transference Device doesn't transfer items to Incinerator's input slot.
It works only when using Storage Bridge.
I have a question then, what are input/output Incinerator slots for?

**Comment by sayterdarkwynd** [comment]
thats because you need a storage bridge.  as for the slots, its old stuff really. it serves only one purpose: deletion

**Comment by VerisZG** [comment]
hey, thanks for the answer, i should correct myself, i meant not the slot which is obvious, but input/output nodes for wiring, what they are for?
