### ISSUE TITLE
Missing asset: extraweaponupgradeanvil.png

### ISSUE THREAD

**Issue by maduin81** [sayterdarkwynd/FrackinUniverse#907]
5.4.282:  File extraweaponupgradeanvil.png is missing and causing a crash on launch

**Comment by theobserver12** [comment]
ah, shit, I knew I left something out. That's what you get for getting overexcited and doing a rush job.

I'll get right on it when I get home from work.

**Comment by maduin81** [comment]
I've been guilty of that, myself, it happens.  Also, if it helps, I'm not overly familiar with mod structure for Starbound, but the entire folder for extraweaponupgradeanvil is empty except for the .object file.  Granted, I've no idea what all would go in there.  You probably already know that, though.

**Comment by theobserver12** [comment]
PR has been made to solve the issue.
