### ISSUE TITLE
Missing Asset stim.itemdescription

### ISSUE THREAD

**Issue by ro9889** [sayterdarkwynd/FrackinUniverse#927]
Fiddling around the game until I discovered the recipe for The Devil's Bargain stim. Tried to view it's description, but the game crashed resulting to displaying this error about missing asset. tried to look around here, yet no results found. Please Advise and thank you for your time.

![error](https://user-images.githubusercontent.com/31377249/29745970-e5fa3416-8afc-11e7-9fed-631c022e8bab.png)

**Comment by shadow-absorber** [comment]
this is not a FU related item there for its not our issue. so we will be closing this issue.
@sayterdarkwynd plz close this none FU issue
