### ISSUE TITLE
Suggestion: Gene Storage Chest to require Cryonic Extract?

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#96]
I see that you've already changed the recipe for the Food Locker to use Cryonic Extract, like a regular Fridge. Thank you.

But, on looking at the Matter Assembler's list more closely, I noticed the Gene Storage Chest. Considering that it is designed to keep DNA samples cold, I think it should also require Cryonic Extract.

Also, while I haven't built one yet, I would assume that it prevents food spoilage like a fridge. Correct? (I can imagine some eccentric or lazy scientist keeping their lunch cold in a Gene Storage fridge or keeping icecream or popsicle treats in a Gene Storage freezer.)

**Comment by renbear67** [comment]
The Gene Storage chest does not keep things from rotting. The name is really a leftover. It's intended for general-purpose storage, now.

**Comment by Thundercraft** [comment]
Okay, that's understandable then. Thanks for the reply.
