### ISSUE TITLE
Extraction Lab: Support for Radioactive Barrels, Junk blocks, and rusted items?

### ISSUE THREAD

**Issue by Thundercraft** [sayterdarkwynd/FrackinUniverse#99]
Why can't we put Radioactive Barrels through the Extraction Lab? I mean... why not? The Extraction Lab will process Barrels of Oil into Oil and it will process Toxic Waste into Uranium Ore x 1. So, I think it's only fair that Radioactive Barrels be processed into Uranium Ore x 1.

Also, I wish that the Extraction Lab would be usable on more materials. Currently, neither Junk Pile blocks ( http://starbounder.org/Junk_Pile ) nor Rusted Metal blocks work. Both are natural blocks found on scorched city planets. Lack of FU support is understandable since these are new as of Cheerful Giraffe. But please add them.

FYI: Junk Pile blocks are loose like gravel or silt, but found abundantly, whereas Rusted Metal blocks are rare. So far, I've mined 927 Junk Pile blocks, but I only found 6 Rusted Metal. I'd love to get -something- out of these (aside from Raw Minerals, that is). I'm hoping for something like a bit of Iron Ore and Silicon from Junk Pile, while Rusted Metal should give something better.

Finally, I would love to get -something- out of Rusted Information Sign, Rusted Console, Broken Console and similar junk, even if it was only a couple bars of metal and/or glass, or a battery or two.

**Comment by sayterdarkwynd** [comment]
dude, youre being a bit silly. The extraction lab has like, 3000 fucking recipes. It works on almost all blocks. Mostly , just not constructed ones. Which is 100% intended.

junk pile and rusted metal blocks haven't been added, but easily can be.

you will not, however, be getting objects to work in the extractor. ever. They are not designed to handle shit like a console or a sign. Its for tiles.
